"use client";
import { useMemo, useState } from "react";
import { ExternalLink, Plus, Search } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useERP } from "@/components/erp-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { money } from "@/lib/files";
import type { Zone } from "@/lib/erp-types";

export default function ClientsPage() {
  const erp = useERP(); const [search, setSearch] = useState(""); const [sort, setSort] = useState("revenue"); const [addOpen, setAddOpen] = useState(false); const [selectedId, setSelectedId] = useState<string | null>(null); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ name: "", phone: "", email: "", zone: 1 as Zone, address: "", locationUrl: "", dietaryNotes: "", strictExclusions: "", preferences: "", isDemo: false });
  const [complaint, setComplaint] = useState({ category: "Quality", details: "" });
  const clients = useMemo(() => erp.clients.filter((x) => `${x.name} ${x.phone}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => { if (sort === "complaints") return erp.complaints.filter((x) => x.clientId === b.id).length - erp.complaints.filter((x) => x.clientId === a.id).length; if (sort === "cancellations") return erp.cancellations.filter((x) => x.clientId === b.id).length - erp.cancellations.filter((x) => x.clientId === a.id).length; return b.totalPaid - a.totalPaid; }), [erp.clients, erp.complaints, erp.cancellations, search, sort]);
  const selected = erp.clients.find((x) => x.id === selectedId); const selectedOrders = erp.orders.filter((x) => x.clientId === selectedId); const selectedDeliveries = erp.deliveries.filter((x) => x.clientId === selectedId); const selectedComplaints = erp.complaints.filter((x) => x.clientId === selectedId); const selectedSubs = erp.subscriptions.filter((x) => x.clientId === selectedId);
  const remaining = selectedSubs.reduce((sum, sub) => { const order = erp.orders.find((x) => x.id === sub.orderId); return sum + (order ? (order.amount / sub.totalDays) * (sub.totalDays - sub.consumedDays) : 0); }, 0);
  async function saveClient() { const r = await erp.addClient({ ...form, strictExclusions: form.strictExclusions.split(",").map((x) => x.trim()).filter(Boolean), preferences: form.preferences.split(",").map((x) => x.trim()).filter(Boolean) }); setMessage(r.message); if (r.ok) setAddOpen(false); }
  async function saveComplaint() { if (!selectedId) return; const r = await erp.addComplaint(selectedId, complaint.category, complaint.details); setMessage(r.message); setComplaint({ category: "Quality", details: "" }); }
  return <AppShell title="العملاء 360°" subtitle="الماليات والتوصيلات والمحاذير والشكاوى في ملف واحد" actions={<Button onClick={() => setAddOpen(true)}><Plus size={17}/>عميل جديد</Button>}>
    {message ? <p className="mb-4 rounded-md bg-[#e8f6ee] p-3 text-sm font-bold text-[#0f603a]">{message}</p> : null}
    <div className="mb-4 grid gap-3 md:grid-cols-[1fr_240px]"><div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-[#8a958e]" size={18}/><Input className="pr-10" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="بحث بالاسم أو الموبايل"/></div><select className="field" value={sort} onChange={(e) => setSort(e.target.value)}><option value="revenue">الأعلى إيرادًا</option><option value="cancellations">الأكثر إلغاءً</option><option value="complaints">الأكثر شكاوى</option></select></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{clients.map((client) => { const orders = erp.orders.filter((x) => x.clientId === client.id); const complaints = erp.complaints.filter((x) => x.clientId === client.id); return <Card key={client.id} className="cursor-pointer transition hover:border-[#70ad89]" onClick={() => setSelectedId(client.id)}><CardContent className="pt-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-black">{client.name}</h2><p className="mt-1 text-sm" dir="ltr">{client.phone}</p></div><Badge>Zone {client.zone}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded bg-[#f3f7f4] p-2"><small>إجمالي الدفع</small><b className="mt-1 block text-sm">{money(client.totalPaid)}</b></div><div className="rounded bg-[#f3f7f4] p-2"><small>الطلبات</small><b className="mt-1 block">{orders.length}</b></div><div className="rounded bg-[#f3f7f4] p-2"><small>الشكاوى</small><b className="mt-1 block">{complaints.length}</b></div></div><p className="mt-4 line-clamp-2 text-sm text-[#66736b]">{client.dietaryNotes || "لا توجد ملاحظات غذائية"}</p></CardContent></Card>; })}</div>
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>تسجيل عميل جديد</DialogTitle></DialogHeader><div className="grid gap-3"><div className="grid grid-cols-2 gap-3"><Input placeholder="الاسم الكامل" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><Input placeholder="رقم الموبايل" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} dir="ltr"/></div><Input type="email" placeholder="البريد الإلكتروني (اختياري)" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/><div className="grid grid-cols-[120px_1fr] gap-3"><select className="field" value={form.zone} onChange={(e) => setForm({ ...form, zone: Number(e.target.value) as Zone })}>{[1,2,3,4].map((z) => <option key={z} value={z}>Zone {z}</option>)}</select><Input placeholder="العنوان بالتفصيل" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })}/></div><Input placeholder="Google Maps link" value={form.locationUrl} onChange={(e) => setForm({ ...form, locationUrl: e.target.value })} dir="ltr"/><Textarea placeholder="ملاحظات غذائية عامة" value={form.dietaryNotes} onChange={(e) => setForm({ ...form, dietaryNotes: e.target.value })}/><Input placeholder="محاذير صارمة مفصولة بفاصلة: No fish, No tuna" value={form.strictExclusions} onChange={(e) => setForm({ ...form, strictExclusions: e.target.value })}/><Input placeholder="تفضيلات مفصولة بفاصلة: Steak, Baladi bread" value={form.preferences} onChange={(e) => setForm({ ...form, preferences: e.target.value })}/><Button onClick={saveClient} disabled={!form.name || !form.phone || !form.address}>حفظ العميل</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelectedId(null)}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{selected?.name} — ملف 360°</DialogTitle></DialogHeader>{selected ? <div><div className="grid gap-3 sm:grid-cols-4"><div className="metric"><small>إجمالي مدفوع</small><b>{money(selected.totalPaid)}</b></div><div className="metric"><small>رصيد متبقٍ</small><b>{money(remaining)}</b></div><div className="metric"><small>إجمالي الطلبات</small><b>{selectedOrders.length}</b></div><div className="metric"><small>إلغاءات</small><b>{erp.cancellations.filter((x) => x.clientId === selected.id).length}</b></div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><section className="rounded-lg border p-4"><h3 className="font-black">العنوان والتواصل</h3><p className="mt-3 text-sm leading-6">{selected.address}</p><a href={selected.locationUrl} target="_blank" className="mt-2 inline-flex items-center gap-1 text-sm font-bold text-[#16794a]">فتح الموقع <ExternalLink size={15}/></a></section><section className="rounded-lg border p-4"><h3 className="font-black">القواعد الغذائية الصارمة</h3><div className="mt-3 flex flex-wrap gap-2">{selected.strictExclusions.map((x) => <Badge key={x} variant="red">{x}</Badge>)}{selected.preferences.map((x) => <Badge key={x}>{x}</Badge>)}</div><p className="mt-3 text-sm">{selected.dietaryNotes}</p></section></div><section className="mt-4 rounded-lg border p-4"><h3 className="font-black">سجل التوصيلات</h3><div className="mt-3 max-h-44 space-y-2 overflow-y-auto">{selectedDeliveries.map((x) => <div key={x.id} className="flex justify-between rounded bg-[#f3f7f4] p-3 text-sm"><span>{x.date} · Zone {x.zone}</span><Badge>{x.status}</Badge></div>)}{!selectedDeliveries.length ? <p className="text-sm text-[#66736b]">لا توجد توصيلات بعد.</p> : null}</div></section><section className="mt-4 rounded-lg border p-4"><h3 className="font-black">الشكاوى والمتابعة</h3><div className="mt-3 grid gap-2">{selectedComplaints.map((x) => <div key={x.id} className="flex items-start justify-between rounded bg-[#f3f7f4] p-3 text-sm"><div><b>{x.category}</b><p className="mt-1">{x.details}</p></div><Button size="sm" variant="outline" disabled={x.status === "Resolved"} onClick={() => erp.resolveComplaint(x.id)}>{x.status === "Resolved" ? "مغلقة" : "إغلاق"}</Button></div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-[150px_1fr_auto]"><select className="field" value={complaint.category} onChange={(e) => setComplaint({ ...complaint, category: e.target.value })}><option>Quality</option><option>Delivery</option><option>Portion</option><option>Payment</option></select><Input placeholder="تفاصيل الشكوى" value={complaint.details} onChange={(e) => setComplaint({ ...complaint, details: e.target.value })}/><Button onClick={saveComplaint} disabled={!complaint.details}>تسجيل</Button></div></section></div> : null}</DialogContent></Dialog>
  </AppShell>;
}
