"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, CheckCheck, ChefHat, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useERP } from "@/components/erp-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { KitchenStatus } from "@/lib/erp-types";

const tomorrow = () => new Date(Date.now() + 86400000).toISOString().slice(0,10);
export default function KitchenPage() {
  const erp = useERP(); const [date, setDate] = useState(tomorrow()); const [from, setFrom] = useState(new Date(Date.now()-7*86400000).toISOString().slice(0,10)); const [to, setTo] = useState(tomorrow()); const [selected, setSelected] = useState<string[]>([]); const [emergencyOpen, setEmergencyOpen] = useState(false); const [emergency, setEmergency] = useState({ clientId: erp.clients[0]?.id ?? "", mealId: erp.meals[0]?.id ?? "" }); const [message, setMessage] = useState("");
  const rows = erp.fulfillment.filter((x) => x.date === date && !x.skipped && ["Sent", "In Prep", "Ready"].includes(x.status));
  const aggregate = useMemo(() => Object.values(rows.reduce<Record<string,{ key:string; meal:string; size:string; count:number; status:KitchenStatus }>>((acc,row) => { const meal = erp.meals.find((x) => x.id === row.mealId)?.name ?? "Unknown"; const key = `${row.mealId}-${row.size}-${row.status}`; acc[key] = acc[key] ?? { key, meal, size: row.size, count: 0, status: row.status }; acc[key].count += 1; return acc; },{})).sort((a,b)=>b.count-a.count), [rows, erp.meals]);
  const volume = erp.fulfillment.filter((x) => x.date >= from && x.date <= to && x.status !== "Planned");
  async function status(value: KitchenStatus) { const ids = selected.length ? selected : rows.map((x) => x.id); const r = await erp.setKitchenStatus(ids, value); setMessage(r.message); setSelected([]); }
  async function emergencySave() { const r = await erp.addEmergencyFulfillment(date, emergency.clientId, emergency.mealId); setMessage(r.message); if (r.ok) setEmergencyOpen(false); }
  return <AppShell title="Kitchen Display System" subtitle="قائمة تجهيز مجمعة وكروت تعبئة كبيرة للمس" actions={<div className="flex gap-2"><input type="date" className="field min-h-11" value={date} onChange={(e) => setDate(e.target.value)}/><Button variant="destructive" onClick={() => setEmergencyOpen(true)}><Plus size={17}/>إضافة طارئة</Button></div>}>
    {message ? <p className="mb-4 rounded-md bg-[#e8f6ee] p-3 text-sm font-bold text-[#0f603a]">{message}</p> : null}
    <Tabs defaultValue="prep"><TabsList className="w-full sm:w-auto"><TabsTrigger value="prep">قائمة التحضير</TabsTrigger><TabsTrigger value="labels">Packing Labels</TabsTrigger><TabsTrigger value="analytics">تحليل الإنتاج</TabsTrigger></TabsList>
      <TabsContent value="prep"><div className="mb-4 grid grid-cols-3 gap-2"><Button size="lg" variant="outline" onClick={() => status("In Prep")} disabled={!rows.length}><ChefHat size={20}/>بدأ التحضير</Button><Button size="lg" onClick={() => status("Ready")} disabled={!rows.length}><CheckCheck size={20}/>جاهز للتوصيل</Button><Button size="lg" variant="outline" onClick={() => setSelected(selected.length === rows.length ? [] : rows.map((x) => x.id))}>{selected.length === rows.length ? "إلغاء التحديد" : "تحديد الكل"}</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{aggregate.map((x) => <Card key={x.key} className={x.status === "Ready" ? "border-[#5cad7a] bg-[#f4fcf7]" : ""}><CardContent className="flex min-h-36 items-center gap-5 pt-5"><span className="flex size-20 shrink-0 items-center justify-center rounded-lg bg-[#10291d] text-3xl font-black text-white">{x.count}</span><div><Badge variant={x.status === "Ready" ? "default" : "orange"}>{x.status}</Badge><h2 className="mt-3 text-xl font-black">{x.meal}</h2><p className="mt-1 font-bold text-[#66736b]">{x.size}</p></div></CardContent></Card>)}{!aggregate.length ? <div className="col-span-full rounded-lg border bg-white p-10 text-center text-[#66736b]">لا توجد بنود معتمدة للمطبخ في هذا التاريخ.</div> : null}</div></TabsContent>
      <TabsContent value="labels"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map((row) => { const client = erp.clients.find((x) => x.id === row.clientId); const meal = erp.meals.find((x) => x.id === row.mealId); const checked = selected.includes(row.id); return <button key={row.id} onClick={() => setSelected(checked ? selected.filter((x) => x !== row.id) : [...selected,row.id])} className={`min-h-44 rounded-lg border-2 bg-white p-5 text-right ${checked ? "border-[#16794a] ring-2 ring-[#bde4cc]" : "border-[#dce5df]"}`}><div className="flex items-start justify-between"><h2 className="text-2xl font-black">{client?.name}</h2><Badge>Zone {row.zone}</Badge></div><p className="mt-3 text-lg font-black text-[#16794a]">{meal?.name}</p><p className="mt-2 font-bold">{row.slot} · {row.size} · Day {row.dayNumber}</p><p className="mt-2 text-sm text-red-700">{client?.strictExclusions.join(" · ") || "لا توجد محاذير"}</p>{row.manualAfterCutoff ? <div className="mt-3 flex items-center gap-2 rounded bg-red-50 p-2 text-sm font-black text-red-800"><AlertTriangle size={17}/>إضافة طارئة</div> : null}</button>; })}</div></TabsContent>
      <TabsContent value="analytics"><div className="mb-4 grid gap-3 sm:grid-cols-2"><label className="rounded border bg-white p-3 text-sm font-bold">من <input type="date" className="field mt-2" value={from} onChange={(e) => setFrom(e.target.value)}/></label><label className="rounded border bg-white p-3 text-sm font-bold">إلى <input type="date" className="field mt-2" value={to} onChange={(e) => setTo(e.target.value)}/></label></div><div className="grid gap-3 sm:grid-cols-3"><div className="metric"><small>إجمالي الوحدات</small><b className="text-3xl">{volume.length}</b></div><div className="metric"><small>Regular</small><b className="text-3xl">{volume.filter((x) => x.size === "Regular").length}</b></div><div className="metric"><small>Hero</small><b className="text-3xl">{volume.filter((x) => x.size === "Hero").length}</b></div></div></TabsContent>
    </Tabs>
    <Dialog open={emergencyOpen} onOpenChange={setEmergencyOpen}><DialogContent><DialogHeader><DialogTitle>إضافة طارئة بعد Cut-off</DialogTitle></DialogHeader><select className="field" value={emergency.clientId} onChange={(e) => setEmergency({ ...emergency, clientId: e.target.value })}>{erp.clients.map((x) => <option key={x.id} value={x.id}>{x.name} · Zone {x.zone}</option>)}</select><select className="field" value={emergency.mealId} onChange={(e) => setEmergency({ ...emergency, mealId: e.target.value })}>{erp.meals.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><Button variant="destructive" onClick={emergencySave}>إضافة وتنبيه المطبخ</Button></DialogContent></Dialog>
  </AppShell>;
}
