"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarOff, ChefHat, RefreshCw, SlidersHorizontal } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { HelpTip } from "@/components/help-tip";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/client";
import type { MealRow, SubscriptionRow } from "@/lib/domain";

const nextDate=()=>new Date().toISOString().slice(0,10);
type Action="pause"|"custom"|null;

export default function SubscriptionsPage(){
  const supabase=useMemo(()=>createClient(),[]); const [subs,setSubs]=useState<SubscriptionRow[]>([]); const [meals,setMeals]=useState<MealRow[]>([]); const [selected,setSelected]=useState<string[]>([]); const [serviceDate,setServiceDate]=useState(nextDate()); const [message,setMessage]=useState(""); const [action,setAction]=useState<Action>(null); const [activeId,setActiveId]=useState<string|null>(null);
  const [pauseUntil,setPauseUntil]=useState(""); const [pauseReason,setPauseReason]=useState(""); const [customDate,setCustomDate]=useState(nextDate()); const [customMeal,setCustomMeal]=useState(""); const [customQty,setCustomQty]=useState("1"); const [priceDelta,setPriceDelta]=useState("0"); const [customReason,setCustomReason]=useState("");
  const load=useCallback(async()=>{const [s,m]=await Promise.all([supabase.from("subscriptions").select("id,client_id,order_id,package_id,status,start_date,delivery_frequency,weekly_delivery_day,total_days,consumed_days,remaining_days,pause_until,clients(full_name,delivery_zone),packages(name,size_name,price),orders(order_number,status,total_price)").order("created_at",{ascending:false}),supabase.from("meals").select("id,name,meal_type,active").eq("active",true).order("name")]);setSubs((s.data??[]) as unknown as SubscriptionRow[]);setMeals((m.data??[]) as MealRow[])},[supabase]); useEffect(()=>{void load()},[load]);
  const active=subs.filter(s=>s.status==="active"); const allSelected=active.length>0&&active.every(s=>selected.includes(s.id)); const current=subs.find(s=>s.id===activeId);
  function toggleAll(){setSelected(allSelected?[]:active.map(s=>s.id))}
  async function sendBulk(){if(selected.length===0){setMessage("اختر اشتراكًا واحدًا على الأقل");return}const {data,error}=await supabase.rpc("bulk_send_to_kitchen",{p_subscription_ids:selected,p_service_date:serviceDate});setMessage(error?.message??`تم إرسال ${data} سطر إنتاج للمطبخ من منيو الشهر`);if(!error)setSelected([])}
  async function pause(){if(!activeId)return;const {error}=await supabase.rpc("pause_subscription",{p_subscription_id:activeId,p_pause_until:pauseUntil||null,p_reason:pauseReason||null});setMessage(error?.message??(pauseUntil?`تم الإيقاف حتى ${pauseUntil}`:"تم الإيقاف إلى أجل غير محدد"));if(!error){setAction(null);await load()}}
  async function resume(id:string){const {error}=await supabase.rpc("resume_subscription",{p_subscription_id:id});setMessage(error?.message??"تم استئناف الاشتراك");if(!error)await load()}
  async function customMenu(){if(!activeId||!customMeal)return;const {error}=await supabase.from("subscription_menu_overrides").insert({subscription_id:activeId,service_date:customDate,meal_id:customMeal,quantity:Number(customQty),custom_price_delta:Number(priceDelta),reason:customReason||null});setMessage(error?.message??"تم حفظ Custom Menu. في هذا التاريخ سيستخدم النظام هذا الاختيار بدل منيو الشهر.");if(!error)setAction(null)}

  return <AppShell title="Advanced Subscriptions" subtitle="Bulk Kitchen، Pause بتاريخ، وCustom Menu لكل عميل">
    {message?<div className="mb-4 rounded-md bg-blue-50 p-3 text-sm font-bold text-blue-900">{message}</div>:null}
    <Card className="mb-4"><CardContent className="pt-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-1 text-sm font-black">Bulk Action <HelpTip text="يقرأ النظام منيو الشهر المنشور أو Custom Menu للعميل، ثم ينشئ Queue فعلية. أي Order غير معتمد من Accounting يتم استبعاده من قاعدة البيانات." /></div><p className="mt-1 text-xs text-[#66736b]">حدد العملاء النشطين المطلوب تجهيزهم في التاريخ.</p></div><div className="flex flex-wrap gap-2"><Input type="date" value={serviceDate} onChange={e=>setServiceDate(e.target.value)} className="w-40"/><Button variant="outline" onClick={toggleAll}>{allSelected?"إلغاء تحديد الكل":"تحديد كل Active"}</Button><Button onClick={sendBulk}><ChefHat size={18}/>Send to Kitchen Queue ({selected.length})</Button></div></div></CardContent></Card>
    <div className="space-y-3">{subs.map(s=><Card key={s.id}><CardContent className="pt-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-start gap-3">{s.status==="active"?<input type="checkbox" className="mt-1 size-5 accent-[#16794a]" checked={selected.includes(s.id)} onChange={e=>setSelected(c=>e.target.checked?[...c,s.id]:c.filter(x=>x!==s.id))}/>:<span className="mt-1 size-5"/>}<div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{s.clients?.full_name}</h2><Badge variant={s.status==="active"?"default":s.status==="paused"?"orange":"gray"}>{s.status}</Badge><Badge variant="gray">Zone {s.clients?.delivery_zone}</Badge></div><p className="mt-1 text-sm font-semibold text-[#536158]">{s.packages?.name} · {s.packages?.size_name} · {s.orders?.order_number}</p><p className="mt-1 text-sm text-[#66736b]">مستهلك {s.consumed_days}/{s.total_days} · باقي {s.remaining_days} يوم · {s.delivery_frequency}{s.pause_until?` · Pause حتى ${s.pause_until}`:""}</p></div></div><div className="flex flex-wrap gap-2">{s.status==="active"?<Button variant="outline" onClick={()=>{setActiveId(s.id);setPauseUntil("");setPauseReason("");setAction("pause")}}><CalendarOff size={17}/>Pause <HelpTip text="يمكن تحديد تاريخ نهاية. عند أول Queue بعد هذا التاريخ يعيد النظام الاشتراك Active تلقائيًا. اترك التاريخ فارغًا للإيقاف المفتوح." /></Button>:null}{s.status==="paused"?<Button onClick={()=>resume(s.id)}><RefreshCw size={17}/>Resume</Button>:null}{["active","paused"].includes(s.status)?<Button variant="outline" onClick={()=>{setActiveId(s.id);setCustomDate(serviceDate);setAction("custom")}}><SlidersHorizontal size={17}/>Custom Menu / Pricing <HelpTip text="يستبدل منيو الشهر لهذا العميل في التاريخ المختار، ويمكن تسجيل فرق سعر خاص بدون تعديل الباكدج الأصلية." /></Button>:null}</div></div></CardContent></Card>)}</div>
    <Dialog open={action==="pause"} onOpenChange={o=>!o&&setAction(null)}><DialogContent><DialogHeader><DialogTitle>Pause — {current?.clients?.full_name}</DialogTitle><DialogDescription>حدد نهاية، أو اتركها فارغة لإيقاف غير محدد.</DialogDescription></DialogHeader><label className="text-sm font-bold">Pause Until (اختياري)</label><Input type="date" value={pauseUntil} onChange={e=>setPauseUntil(e.target.value)}/><label className="mt-3 text-sm font-bold">السبب</label><Input value={pauseReason} onChange={e=>setPauseReason(e.target.value)} placeholder="سفر / طلب العميل..."/><Button className="mt-4 w-full" onClick={pause}>تأكيد الإيقاف</Button></DialogContent></Dialog>
    <Dialog open={action==="custom"} onOpenChange={o=>!o&&setAction(null)}><DialogContent><DialogHeader><DialogTitle>Custom Menu — {current?.clients?.full_name}</DialogTitle><DialogDescription>هذا التعديل خاص بالعميل فقط ولا يغير منيو باقي المشتركين.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">التاريخ</label><Input type="date" value={customDate} onChange={e=>setCustomDate(e.target.value)}/></div><div><label className="mb-2 block text-sm font-bold">الوجبة</label><select value={customMeal} onChange={e=>setCustomMeal(e.target.value)} className="min-h-11 w-full rounded-md border border-[#cfdad3] bg-white px-3"><option value="">اختر</option>{meals.map(m=><option key={m.id} value={m.id}>{m.name} · {m.meal_type}</option>)}</select></div><div><label className="mb-2 block text-sm font-bold">الكمية</label><Input type="number" min="1" value={customQty} onChange={e=>setCustomQty(e.target.value)}/></div><div><label className="mb-2 block text-sm font-bold">فرق السعر EGP</label><Input type="number" value={priceDelta} onChange={e=>setPriceDelta(e.target.value)}/></div></div><Input className="mt-3" value={customReason} onChange={e=>setCustomReason(e.target.value)} placeholder="سبب التخصيص"/><Button className="mt-4 w-full" onClick={customMenu}>حفظ Custom Menu</Button></DialogContent></Dialog>
  </AppShell>
}
