import "server-only";

import { createClient } from "@/lib/supabase/server";
import type { Viewer } from "@/lib/auth/viewer";

export type ModuleKey = "projects" | "tasks" | "leads" | "customers" | "sales" | "invoices" | "finance" | "subscriptions" | "operations" | "complaints" | "performance" | "doctors" | "calendar" | "sessions" | "doctorAccounting" | "notifications";
export type ModuleRow = Record<string, string | number>;

type ModuleConfig = {
  eyebrow: string;
  title: string;
  description: string;
  table: string;
  statusField: string;
  columns: { key: string; label: string }[];
  previewRows: ModuleRow[];
  kpis: { label: string; value: string; tone: "green" | "amber" | "blue" | "red" }[];
  workflow?: "project" | "task" | "lead" | "customer" | "complaint" | "payment" | "session" | "notification";
};

export const moduleConfigs: Record<ModuleKey, ModuleConfig> = {
  projects: { eyebrow: "Projects", title: "المشروعات", description: "متابعة المشاريع الاستراتيجية والتقدم والمخاطر والمهام المرتبطة.", table: "projects", statusField: "status", workflow: "project", columns: [{ key: "name", label: "المشروع" }, { key: "owner", label: "المالك" }, { key: "status", label: "الحالة" }, { key: "progress", label: "التقدم" }], previewRows: [{ name: "إطلاق التشغيل الجديد", owner: "منى أحمد", status: "نشط", progress: "68%" }, { name: "برنامج تحسين الاحتفاظ", owner: "سارة علي", status: "معرض للخطر", progress: "42%" }, { name: "تكامل التقويم", owner: "فريق التقنية", status: "مخطط", progress: "15%" }], kpis: [{ label: "مشروعات نشطة", value: "8", tone: "green" }, { label: "معرضة للخطر", value: "2", tone: "red" }, { label: "متوسط التقدم", value: "61%", tone: "blue" }, { label: "قرارات معلقة", value: "3", tone: "amber" }] },
  tasks: { eyebrow: "Work management", title: "المهام والمتابعات", description: "My Tasks وTeam Queue والردود الرسمية والأدلة والمراجعة والتصعيد.", table: "tasks", statusField: "status", workflow: "task", columns: [{ key: "title", label: "المهمة" }, { key: "assignee", label: "المسند إليه" }, { key: "due", label: "الموعد" }, { key: "status", label: "الحالة" }], previewRows: [{ title: "متابعة عرض أحمد", assignee: "محمد - Sales", due: "اليوم 3:00", status: "بانتظار الرد" }, { title: "مراجعة إثبات الإكمال", assignee: "سارة - Reviewer", due: "غدًا", status: "قيد المراجعة" }, { title: "قرار حملة أكتوبر", assignee: "CEO", due: "بدون موعد", status: "مفتوحة" }], kpis: [{ label: "مهامي", value: "12", tone: "green" }, { label: "متأخرة", value: "3", tone: "red" }, { label: "بانتظار ردي", value: "4", tone: "amber" }, { label: "بدون موعد", value: "5", tone: "blue" }] },
  leads: { eyebrow: "CRM", title: "العملاء المحتملون", description: "توزيع العملاء المحتملين والمتابعة والتحويل مع SLA وTimeline.", table: "leads", statusField: "status", workflow: "lead", columns: [{ key: "name", label: "العميل المحتمل" }, { key: "source", label: "المصدر" }, { key: "owner", label: "المسؤول" }, { key: "status", label: "الحالة" }], previewRows: [{ name: "محمود سامي", source: "Instagram", owner: "أحمد", status: "مؤهل" }, { name: "نور خالد", source: "Referral", owner: "مريم", status: "عرض" }, { name: "هاني عماد", source: "Website", owner: "أحمد", status: "جديد" }], kpis: [{ label: "Leads جديدة", value: "34", tone: "blue" }, { label: "Hot", value: "9", tone: "red" }, { label: "متابعة اليوم", value: "11", tone: "amber" }, { label: "تحويل هذا الشهر", value: "27%", tone: "green" }] },
  customers: { eyebrow: "Customer 360", title: "العملاء", description: "ملف موحد للعناوين والتفضيلات والحساسيات والملاحظات والتاريخ.", table: "customers", statusField: "status", workflow: "customer", columns: [{ key: "name", label: "العميل" }, { key: "mobile", label: "الهاتف" }, { key: "plan", label: "الخطة" }, { key: "status", label: "الحالة" }], previewRows: [{ name: "أحمد محمد", mobile: "0100••••102", plan: "Eco 30", status: "نشط" }, { name: "منى حسن", mobile: "0111••••345", plan: "Consultation", status: "جديد" }, { name: "ياسمين طارق", mobile: "0122••••670", plan: "Eco 60", status: "نشط" }], kpis: [{ label: "عملاء نشطون", value: "428", tone: "green" }, { label: "بحاجة متابعة", value: "19", tone: "amber" }, { label: "تفضيلات محدثة", value: "86%", tone: "blue" }, { label: "تحذيرات حساسية", value: "14", tone: "red" }] },
  sales: { eyebrow: "Commercial", title: "المبيعات والباقات", description: "باقات وإصدارات أسعار وعروض أسعار وحدود خصم قابلة للتتبع.", table: "quotations", statusField: "status", columns: [{ key: "number", label: "العرض" }, { key: "customer", label: "العميل" }, { key: "amount", label: "الإجمالي" }, { key: "status", label: "الحالة" }], previewRows: [{ number: "Q-1042", customer: "أحمد محمد", amount: "5,700 EGP", status: "مقبول" }, { number: "Q-1041", customer: "نور خالد", amount: "8,400 EGP", status: "صادر" }, { number: "Q-1039", customer: "هاني عماد", amount: "3,200 EGP", status: "مسودة" }], kpis: [{ label: "عروض مفتوحة", value: "18", tone: "blue" }, { label: "قيمة Pipeline", value: "184K", tone: "green" }, { label: "خصومات معلقة", value: "4", tone: "amber" }, { label: "Conversion", value: "31%", tone: "green" }] },
  invoices: { eyebrow: "Billing", title: "الفواتير", description: "فواتير مرتبطة بعروض الأسعار والتحصيل المؤكد دون خلط الإثبات بالنقد.", table: "invoices", statusField: "status", columns: [{ key: "number", label: "الفاتورة" }, { key: "customer", label: "العميل" }, { key: "total", label: "الإجمالي" }, { key: "status", label: "الحالة" }], previewRows: [{ number: "INV-2088", customer: "أحمد محمد", total: "5,700 EGP", status: "مدفوعة" }, { number: "INV-2087", customer: "منى حسن", total: "700 EGP", status: "بانتظار الدفع" }, { number: "INV-2085", customer: "ياسمين طارق", total: "12,000 EGP", status: "مدفوعة جزئيًا" }], kpis: [{ label: "صادرة", value: "26", tone: "blue" }, { label: "Confirmed Cash", value: "312K", tone: "green" }, { label: "قيد المراجعة", value: "7", tone: "amber" }, { label: "متأخرة", value: "5", tone: "red" }] },
  finance: { eyebrow: "Maker-Checker", title: "مراجعة المدفوعات", description: "Payment Proof يبقى Pending حتى يؤكده Finance من مستخدم مختلف.", table: "payment_submissions", statusField: "status", workflow: "payment", columns: [{ key: "reference", label: "المرجع" }, { key: "customer", label: "العميل" }, { key: "claimed", label: "المبلغ المدعى" }, { key: "status", label: "الحالة" }], previewRows: [{ reference: "PAY-8831", customer: "أحمد محمد", claimed: "5,700 EGP", status: "مؤكد" }, { reference: "PAY-8832", customer: "منى حسن", claimed: "700 EGP", status: "قيد المراجعة" }, { reference: "PAY-8833", customer: "نور خالد", claimed: "4,200 EGP", status: "Pending" }], kpis: [{ label: "Pending Proofs", value: "7", tone: "amber" }, { label: "Confirmed Today", value: "48K", tone: "green" }, { label: "Unallocated", value: "6K", tone: "blue" }, { label: "Refunds", value: "2", tone: "red" }] },
  subscriptions: { eyebrow: "Subscriptions", title: "الاشتراكات", description: "التفعيل والتجميد والإلغاء والرصيد المؤجل والخدمة المؤكدة.", table: "subscriptions", statusField: "status", columns: [{ key: "number", label: "الاشتراك" }, { key: "customer", label: "العميل" }, { key: "remaining", label: "الأيام المتبقية" }, { key: "status", label: "الحالة" }], previewRows: [{ number: "SUB-1402", customer: "أحمد محمد", remaining: "29", status: "نشط" }, { number: "SUB-1398", customer: "ياسمين طارق", remaining: "17", status: "مجمد" }, { number: "SUB-1380", customer: "محمود سامي", remaining: "3", status: "قرب التجديد" }], kpis: [{ label: "نشطة", value: "311", tone: "green" }, { label: "مجمدة", value: "18", tone: "blue" }, { label: "تجديد خلال 7 أيام", value: "27", tone: "amber" }, { label: "At Risk", value: "12", tone: "red" }] },
  operations: { eyebrow: "Daily operations", title: "مركز عمليات المشتركين", description: "قائمة الخدمة اليومية تفصل المخطط عنDelivered/Confirmed وتمنع الاعتراف الخاطئ.", table: "planned_service_days", statusField: "status", columns: [{ key: "customer", label: "المشترك" }, { key: "package", label: "الباقة" }, { key: "branch", label: "الفرع" }, { key: "status", label: "حالة اليوم" }], previewRows: [{ customer: "أحمد محمد", package: "Eco 30", branch: "الرئيسي", status: "Confirmed Delivered" }, { customer: "ياسمين طارق", package: "Eco 60", branch: "الثاني", status: "Frozen" }, { customer: "محمود سامي", package: "Eco 30", branch: "الرئيسي", status: "Planned" }], kpis: [{ label: "مخطط اليوم", value: "146", tone: "blue" }, { label: "مؤكد التسليم", value: "118", tone: "green" }, { label: "مجمد", value: "9", tone: "amber" }, { label: "استثناءات", value: "4", tone: "red" }] },
  complaints: { eyebrow: "Service quality", title: "الشكاوى", description: "SLA وRoot Cause وCorrective Action وقياس الرضا بعد الحل.", table: "complaints", statusField: "status", workflow: "complaint", columns: [{ key: "number", label: "الشكوى" }, { key: "customer", label: "العميل" }, { key: "category", label: "التصنيف" }, { key: "status", label: "الحالة" }], previewRows: [{ number: "CMP-302", customer: "أحمد محمد", category: "تأخر الرد", status: "قيد التحقيق" }, { number: "CMP-299", customer: "منى حسن", category: "حجز جلسة", status: "محلولة" }, { number: "CMP-296", customer: "نور خالد", category: "جودة", status: "بانتظار العميل" }], kpis: [{ label: "مفتوحة", value: "13", tone: "amber" }, { label: "Critical", value: "1", tone: "red" }, { label: "ضمن SLA", value: "91%", tone: "green" }, { label: "رضا الحل", value: "4.4", tone: "blue" }] },
  performance: { eyebrow: "Performance", title: "الأهداف والعمولات", description: "الأداء مبني على Confirmed Cash فقط مع Team Bonus وClawback.", table: "sales_targets", statusField: "status", columns: [{ key: "owner", label: "الموظف" }, { key: "target", label: "الهدف" }, { key: "actual", label: "المؤكد" }, { key: "status", label: "الإنجاز" }], previewRows: [{ owner: "أحمد", target: "120K", actual: "102K", status: "85%" }, { owner: "مريم", target: "100K", actual: "111K", status: "111%" }, { owner: "فريق المبيعات", target: "420K", actual: "362K", status: "86%" }], kpis: [{ label: "Confirmed Cash", value: "362K", tone: "green" }, { label: "Achievement", value: "86%", tone: "blue" }, { label: "Eligible Commission", value: "18.4K", tone: "amber" }, { label: "Clawbacks", value: "1.2K", tone: "red" }] },
  doctors: { eyebrow: "Doctor master", title: "دليل الأطباء", description: "التخصصات والفروع والخدمات والتعاقد، مع حجب البيانات المالية عن Sales.", table: "doctors", statusField: "status", columns: [{ key: "name", label: "الطبيب" }, { key: "specialty", label: "التخصص" }, { key: "mode", label: "النمط" }, { key: "status", label: "الحالة" }], previewRows: [{ name: "د. سارة علي", specialty: "تغذية علاجية", mode: "Online / Onsite", status: "نشط" }, { name: "د. عمر حسن", specialty: "Medical Review", mode: "Onsite", status: "نشط" }, { name: "د. ليلى سمير", specialty: "Nutrition", mode: "Online", status: "نشط" }], kpis: [{ label: "أطباء نشطون", value: "12", tone: "green" }, { label: "تخصصات", value: "6", tone: "blue" }, { label: "متوسط التقييم", value: "4.8", tone: "green" }, { label: "Pending Notes", value: "5", tone: "amber" }] },
  calendar: { eyebrow: "Availability", title: "تقويم الأطباء", description: "Slots المتاحة والمحجوزة والإجازات ومنع Double Booking.", table: "doctor_slots", statusField: "status", columns: [{ key: "time", label: "الوقت" }, { key: "doctor", label: "الطبيب" }, { key: "branch", label: "الفرع" }, { key: "status", label: "الحالة" }], previewRows: [{ time: "09:00 - 09:45", doctor: "د. سارة", branch: "الرئيسي", status: "متاح" }, { time: "10:00 - 10:45", doctor: "د. سارة", branch: "Online", status: "محجوز" }, { time: "12:00 - 13:00", doctor: "د. عمر", branch: "الرئيسي", status: "متاح" }], kpis: [{ label: "Available Today", value: "28", tone: "green" }, { label: "Booked", value: "17", tone: "blue" }, { label: "Held", value: "3", tone: "amber" }, { label: "Conflicts", value: "0", tone: "green" }] },
  sessions: { eyebrow: "Doctor sessions", title: "جلسات الأطباء", description: "الحجز والدفع والتأكيد والإسناد والملاحظات والتوصية والمتابعة.", table: "doctor_sessions", statusField: "status", workflow: "session", columns: [{ key: "number", label: "الجلسة" }, { key: "customer", label: "العميل" }, { key: "doctor", label: "الطبيب" }, { key: "status", label: "الحالة" }], previewRows: [{ number: "SES-2051", customer: "أحمد محمد", doctor: "د. سارة", status: "Scheduled" }, { number: "SES-2048", customer: "منى حسن", doctor: "د. عمر", status: "Completed" }, { number: "SES-2046", customer: "نور خالد", doctor: "د. ليلى", status: "No-Show" }], kpis: [{ label: "جلسات اليوم", value: "17", tone: "blue" }, { label: "بانتظار الدفع", value: "4", tone: "amber" }, { label: "Completed", value: "9", tone: "green" }, { label: "No-Show", value: "1", tone: "red" }] },
  doctorAccounting: { eyebrow: "Doctor subledger", title: "حسابات الأطباء", description: "Eligible/Approved/Paid/Outstanding وكشوف شهرية وضوابط Maker–Checker.", table: "doctor_commission_entries", statusField: "status", columns: [{ key: "doctor", label: "الطبيب" }, { key: "source", label: "المصدر" }, { key: "amount", label: "العمولة" }, { key: "status", label: "الحالة" }], previewRows: [{ doctor: "د. سارة", source: "Session SES-2048", amount: "250 EGP", status: "Approved" }, { doctor: "د. عمر", source: "Plan Recommendation", amount: "380 EGP", status: "Eligible" }, { doctor: "د. ليلى", source: "Monthly Statement", amount: "2,100 EGP", status: "Paid" }], kpis: [{ label: "Eligible", value: "14.8K", tone: "amber" }, { label: "Approved", value: "11.2K", tone: "blue" }, { label: "Paid This Month", value: "32K", tone: "green" }, { label: "Outstanding", value: "7.4K", tone: "red" }] },
  notifications: { eyebrow: "Provider architecture", title: "الإشعارات والتكاملات", description: "In-App وEmail وWhatsApp وCalendar عبر Outbox وRetry وIdempotency.", table: "notification_messages", statusField: "status", workflow: "notification", columns: [{ key: "event", label: "الحدث" }, { key: "channel", label: "القناة" }, { key: "recipient", label: "المستلم" }, { key: "status", label: "الحالة" }], previewRows: [{ event: "Task Assigned", channel: "In-App", recipient: "أحمد", status: "Delivered" }, { event: "Booking Confirmed", channel: "Email Mock", recipient: "Customer", status: "Delivered" }, { event: "Meet Link Created", channel: "WhatsApp Mock", recipient: "Doctor", status: "Queued" }], kpis: [{ label: "Queued", value: "6", tone: "amber" }, { label: "Delivered", value: "184", tone: "green" }, { label: "Retries", value: "2", tone: "blue" }, { label: "Failed", value: "1", tone: "red" }] },
};

function normalizeRow(row: Record<string, unknown>, config: ModuleConfig): ModuleRow {
  const entries = config.columns.map(({ key }) => {
    const direct = row[key];
    if (direct !== undefined && direct !== null) return [key, typeof direct === "number" ? direct : String(direct)];
    if (key === "name") return [key, String(row.full_name || row.title || row.name || "—")];
    if (key === "number") return [key, String(row.quotation_number || row.invoice_number || row.subscription_number || row.session_number || row.complaint_number || "—")];
    if (key === "status") return [key, String(row[config.statusField] || "—")];
    if (key === "amount" || key === "total" || key === "claimed") return [key, String(row.total_amount || row.claimed_amount || row.amount || "—")];
    if (key === "progress") return [key, `${row.progress_percent || 0}%`];
    if (key === "due") return [key, String(row.due_at || "بدون موعد")];
    return [key, "—"];
  });
  return Object.fromEntries(entries) as ModuleRow;
}

export async function getModuleView(viewer: Viewer, key: ModuleKey) {
  const config = moduleConfigs[key];
  if (viewer.preview) return { ...config, rows: config.previewRows };
  const supabase = await createClient();
  const branchFields: Partial<Record<ModuleKey, "branch_id" | "home_branch_id">> = {
    projects: "branch_id", tasks: "branch_id", leads: "branch_id", customers: "home_branch_id",
    sales: "branch_id", invoices: "branch_id", finance: "branch_id", subscriptions: "branch_id",
    operations: "branch_id", complaints: "branch_id", performance: "branch_id", calendar: "branch_id",
    sessions: "branch_id", doctorAccounting: "branch_id", notifications: "branch_id",
  };
  let query = supabase.from(config.table).select("*").limit(25);
  const branchField = branchFields[key];
  if (branchField && viewer.activeBranchId) query = query.eq(branchField, viewer.activeBranchId);
  const { data, error } = await query;
  if (error) throw new Error(`${config.title} load failed: ${error.message}`);
  const rawRows = (data || []) as Record<string, unknown>[];
  const openStates = new Set(["active", "open", "assigned", "accepted", "in_progress", "requested", "pending", "under_review", "planned", "scheduled", "queued"]);
  const attentionStates = new Set(["at_risk", "blocked", "overdue", "rejected", "failed", "exception", "waiting_for_approval", "waiting_for_feedback"]);
  const closedStates = new Set(["completed", "closed", "paid", "confirmed", "delivered", "cancelled", "resolved"]);
  const statuses = rawRows.map((row) => String(row[config.statusField] || "").toLowerCase());
  const liveKpis: ModuleConfig["kpis"] = [
    { label: "إجمالي السجلات", value: String(rawRows.length), tone: "blue" },
    { label: "مفتوحة / نشطة", value: String(statuses.filter((status) => openStates.has(status)).length), tone: "green" },
    { label: "تحتاج متابعة", value: String(statuses.filter((status) => attentionStates.has(status)).length), tone: "red" },
    { label: "مغلقة / مكتملة", value: String(statuses.filter((status) => closedStates.has(status)).length), tone: "amber" },
  ];
  return { ...config, kpis: liveKpis, rows: rawRows.map((row) => normalizeRow(row, config)) };
}
