export function DocumentSheet({ id, title, number, children }: { id: string; title: string; number: string; children: React.ReactNode }) {
  return <div id={id} className="fixed -left-[9999px] top-0 w-[794px] bg-white p-12 text-[#17211b]" dir="rtl">
    <div className="flex items-start justify-between border-b-4 border-[#16794a] pb-6">
      <div><div className="inline-flex rounded bg-[#16794a] px-4 py-2 text-xl font-black text-white">ECO HEALTHY</div><p className="mt-2 text-sm text-[#66736b]">Healthy Meals & Subscriptions</p></div>
      <div className="text-left"><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 font-bold" dir="ltr">#{number}</p><p className="mt-1 text-sm">{new Date().toLocaleDateString("ar-EG")}</p></div>
    </div>
    <div className="py-8">{children}</div>
    <div className="mt-10 border-t border-[#dce5df] pt-5 text-center text-xs text-[#66736b]">ECO Healthy · Cairo, Egypt · Generated by ECO Healthy ERP</div>
  </div>;
}
