"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { FileDown, Plus, ReceiptText, ShoppingBag } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { HelpTip } from "@/components/help-tip";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { exportElementToPdf, uploadPaymentProof } from "@/lib/export-tools";
import { createClient } from "@/lib/supabase/client";
import type { ClientRow, MealRow, OrderRow, PackageRow } from "@/lib/domain";

type AdhocItem={meal_id:string;service_date:string;quantity:number;unit_price:number;notes:string};
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};

export default function OrdersPage(){
  const supabase=useMemo(()=>createClient(),[]); const [clients,setClients]=useState<ClientRow[]>([]); const [packages,setPackages]=useState<PackageRow[]>([]); const [meals,setMeals]=useState<MealRow[]>([]); const [orders,setOrders]=useState<OrderRow[]>([]);
  const [type,setType]=useState<"subscription"|"adhoc">("subscription"); const [clientId,setClientId]=useState(""); const [packageId,setPackageId]=useState(""); const [startDate,setStartDate]=useState(tomorrow()); const [frequency,setFrequency]=useState<"daily"|"weekly">("daily"); const [weeklyDay,setWeeklyDay]=useState("6");
  const [payment,setPayment]=useState<"cash"|"instapay"|"website_app">("cash"); const [reference,setReference]=useState(""); const [proof,setProof]=useState<File|null>(null); const [items,setItems]=useState<AdhocItem[]>([{meal_id:"",service_date:tomorrow(),quantity:1,unit_price:0,notes:""}]);
  const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [created,setCreated]=useState<OrderRow|null>(null);

  const load=useCallback(async()=>{const [c,p,m,o]=await Promise.all([supabase.from("clients").select("*").eq("active",true).order("full_name"),supabase.from("packages").select("id,name,size_name,number_of_days,price,active").eq("active",true).order("name"),supabase.from("meals").select("id,name,meal_type,active").eq("active",true).order("name"),supabase.from("orders").select("id,order_number,client_id,order_type,total_price,payment_method,payment_reference,payment_proof_path,status,accounting_verified_at,created_at,clients(full_name,phone)").order("created_at",{ascending:false}).limit(20)]);setClients((c.data??[]) as ClientRow[]);setPackages((p.data??[]) as PackageRow[]);setMeals((m.data??[]) as MealRow[]);setOrders((o.data??[]) as unknown as OrderRow[])},[supabase]);
  useEffect(()=>{void load()},[load]);
  const selectedClient=clients.find(c=>c.id===clientId); const selectedPackage=packages.find(p=>p.id===packageId); const adhocTotal=items.reduce((s,i)=>s+i.quantity*i.unit_price,0);

  function updateItem(index:number,patch:Partial<AdhocItem>){setItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item))}
  async function createOrder(){
    if(!clientId){setMessage("اختر العميل أولاً");return} if(type==="subscription"&&!packageId){setMessage("اختر الباكدج");return} if(type==="adhoc"&&items.some(i=>!i.meal_id||i.unit_price<=0)){setMessage("أكمل بيانات كل وجبات الـAd-Hoc");return}
    if(payment!=="cash"&&(!reference.trim()||!proof)){setMessage("Reference وصورة إثبات الدفع مطلوبان لـ InstaPay / Website");return}
    setSaving(true);setMessage("");
    try{let proofPath:string|null=null;if(proof)proofPath=await uploadPaymentProof(proof);const {data,error}=await supabase.rpc("create_sales_order",{p_client_id:clientId,p_order_type:type,p_package_id:type==="subscription"?packageId:null,p_start_date:type==="subscription"?startDate:null,p_delivery_frequency:frequency,p_weekly_delivery_day:frequency==="weekly"?Number(weeklyDay):null,p_payment_method:payment,p_payment_reference:reference.trim()||null,p_payment_proof_path:proofPath,p_adhoc_items:type==="adhoc"?items:[]});if(error)throw error;const {data:order,error:orderError}=await supabase.from("orders").select("id,order_number,client_id,order_type,total_price,payment_method,payment_reference,payment_proof_path,status,accounting_verified_at,created_at,clients(full_name,phone)").eq("id",data).single();if(orderError)throw orderError;setCreated(order as unknown as OrderRow);setMessage("تم إنشاء الطلب وإرساله إلى Pending Accounting. لن يدخل المطبخ قبل اعتماد الحسابات.");await load()}catch(e:any){setMessage(e.message??"حدث خطأ")}finally{setSaving(false)}
  }

  return <AppShell title="الطلبات والمبيعات" subtitle="Subscription أو Ad-Hoc مع Payment Proof وفاتورة PDF">
    {message?<div className="mb-4 rounded-md bg-blue-50 p-3 text-sm font-bold text-blue-900">{message}</div>:null}
    <div className="grid gap-5 2xl:grid-cols-[1.25fr_.75fr]">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShoppingBag size={21}/>New Order <HelpTip text="أي Order جديد يظل Pending Accounting. قاعدة البيانات تمنعه من Kitchen حتى يضغط Accounting على Confirm." /></CardTitle></CardHeader><CardContent className="space-y-5">
        <div className="grid grid-cols-2 gap-2"><Button variant={type==="subscription"?"default":"outline"} onClick={()=>setType("subscription")}>Subscription</Button><Button variant={type==="adhoc"?"default":"outline"} onClick={()=>setType("adhoc")}>Ad-Hoc / One-Off</Button></div>
        <div><label className="mb-2 block text-sm font-bold">العميل</label><select value={clientId} onChange={e=>setClientId(e.target.value)} className="min-h-12 w-full rounded-md border border-[#cfdad3] bg-white px-3"><option value="">اختر العميل</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone}</option>)}</select></div>
        {type==="subscription"?<div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">الباكدج / الحجم</label><select value={packageId} onChange={e=>setPackageId(e.target.value)} className="min-h-12 w-full rounded-md border border-[#cfdad3] bg-white px-3"><option value="">اختر الباكدج</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name} · {p.size_name} · {p.number_of_days} يوم · {Number(p.price).toLocaleString()} ج</option>)}</select></div><div><label className="mb-2 block text-sm font-bold">تاريخ البداية</label><Input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div><label className="mb-2 block text-sm font-bold">Frequency</label><select value={frequency} onChange={e=>setFrequency(e.target.value as any)} className="min-h-12 w-full rounded-md border border-[#cfdad3] bg-white px-3"><option value="daily">Normal / Daily</option><option value="weekly">Weekly</option></select></div>{frequency==="weekly"?<div><label className="mb-2 block text-sm font-bold">يوم الأسبوع</label><select value={weeklyDay} onChange={e=>setWeeklyDay(e.target.value)} className="min-h-12 w-full rounded-md border border-[#cfdad3] bg-white px-3"><option value="1">الاثنين</option><option value="2">الثلاثاء</option><option value="3">الأربعاء</option><option value="4">الخميس</option><option value="5">الجمعة</option><option value="6">السبت</option><option value="7">الأحد</option></select></div>:null}</div>:
        <div><div className="mb-2 flex items-center justify-between"><label className="text-sm font-bold">وجبات الـAd-Hoc</label><Button size="sm" variant="outline" onClick={()=>setItems(c=>[...c,{meal_id:"",service_date:tomorrow(),quantity:1,unit_price:0,notes:""}])}><Plus size={15}/>إضافة وجبة</Button></div><div className="space-y-2">{items.map((item,index)=><div key={index} className="grid gap-2 rounded-md bg-[#f5f8f6] p-3 sm:grid-cols-4"><select value={item.meal_id} onChange={e=>updateItem(index,{meal_id:e.target.value})} className="min-h-11 rounded-md border border-[#cfdad3] bg-white px-2 text-sm"><option value="">الوجبة</option>{meals.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><Input type="date" value={item.service_date} onChange={e=>updateItem(index,{service_date:e.target.value})}/><Input type="number" min="1" value={item.quantity} onChange={e=>updateItem(index,{quantity:Number(e.target.value)})} placeholder="Qty"/><Input type="number" min="0" value={item.unit_price||""} onChange={e=>updateItem(index,{unit_price:Number(e.target.value)})} placeholder="Unit Price"/></div>)}</div><p className="mt-2 text-left text-lg font-black" dir="ltr">Total: {adhocTotal.toLocaleString()} EGP</p></div>}
        <div className="border-t border-[#e1e8e3] pt-5"><div className="mb-2 flex items-center gap-1 text-sm font-bold">Payment Capture <HelpTip text="Cash لا يحتاج صورة. InstaPay وWebsite/App يحتاجان Reference وصورة إثبات إلزاميًا قبل حفظ الطلب." /></div><div className="grid gap-3 sm:grid-cols-3"><Button variant={payment==="cash"?"default":"outline"} onClick={()=>setPayment("cash")}>Cash</Button><Button variant={payment==="instapay"?"default":"outline"} onClick={()=>setPayment("instapay")}>InstaPay</Button><Button variant={payment==="website_app"?"default":"outline"} onClick={()=>setPayment("website_app")}>Website / App</Button></div>{payment!=="cash"?<div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference / Order ID"/><label className="flex min-h-11 cursor-pointer items-center justify-center rounded-md border border-dashed border-[#9daaa1] bg-white px-3 text-sm font-bold text-[#536158]"><input type="file" accept="image/*,application/pdf" className="hidden" onChange={e=>setProof(e.target.files?.[0]??null)}/>{proof?proof.name:"Upload payment screenshot"}</label></div>:null}</div>
        <Button size="lg" className="w-full min-h-14" onClick={createOrder} disabled={saving}>{saving?"جاري الحفظ...":"إنشاء الطلب وإرساله للحسابات"}</Button>
      </CardContent></Card>
      <div className="space-y-4">{created?<><Card><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptText size={20}/>Invoice Ready</CardTitle></CardHeader><CardContent><div id="invoice-document" className="rounded-md bg-white p-6 text-[#17211b]"><div className="mb-6 flex items-center justify-between border-b border-[#dce5df] pb-4"><div className="flex size-16 items-center justify-center rounded-md bg-[#16794a] font-black text-white">LOGO</div><div className="text-left" dir="ltr"><b>ECO Healthy</b><p className="text-xs text-[#66736b]">INVOICE</p></div></div><p className="text-sm text-[#66736b]">Invoice No.</p><p className="font-black">{created.order_number}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-[#66736b]">Client</p><b>{created.clients?.full_name}</b></div><div><p className="text-[#66736b]">Type</p><b>{created.order_type}</b></div><div><p className="text-[#66736b]">Payment</p><b>{created.payment_method}</b></div><div><p className="text-[#66736b]">Status</p><b>{created.status}</b></div></div><div className="mt-6 border-t border-[#dce5df] pt-4 text-2xl font-black">Total: {Number(created.total_price).toLocaleString("ar-EG")} EGP</div></div><Button className="mt-3 w-full" variant="outline" onClick={()=>exportElementToPdf("invoice-document",`${created.order_number}.pdf`)}><FileDown size={18}/>Download PDF Invoice</Button></CardContent></Card></>:null}
        <Card><CardHeader><CardTitle>آخر الطلبات</CardTitle></CardHeader><CardContent className="space-y-2">{orders.map(o=><div key={o.id} className="rounded-md border border-[#e2e9e4] p-3"><div className="flex items-center justify-between gap-2"><b>{o.order_number}</b><Badge variant={o.status==="confirmed"?"default":o.status==="pending_accounting"?"orange":"gray"}>{o.status}</Badge></div><p className="mt-1 text-sm text-[#66736b]">{o.clients?.full_name} · {o.order_type} · {Number(o.total_price).toLocaleString()} ج</p></div>)}</CardContent></Card>
      </div>
    </div>
  </AppShell>
}
