export type Role = "admin" | "sales" | "cs" | "kitchen" | "delivery" | "accounting";

export type EmployeeProfile = { user_id: string; full_name: string; role: Role; active: boolean };
export type ClientRow = { id: string; full_name: string; phone: string; delivery_zone: number; location_url: string | null; address_text: string | null; dietary_notes: string | null; created_at: string };
export type MealRow = { id: string; name: string; meal_type: "standard" | "lc" | "high_protein"; active: boolean };
export type PackageRow = { id: string; name: string; size_name: string; number_of_days: number; price: number; active: boolean };
export type MenuItemRow = { id: string; service_date: string; package_id: string; meal_id: string; quantity: number; meals?: { name: string; meal_type: string } | null; packages?: { name: string; size_name: string } | null };
export type OrderRow = { id: string; order_number: string; client_id: string; order_type: "subscription" | "adhoc"; total_price: number; payment_method: "cash" | "instapay" | "website_app"; payment_reference: string | null; payment_proof_path: string | null; status: "pending_accounting" | "confirmed" | "rejected" | "canceled" | "refunded"; accounting_verified_at: string | null; created_at: string; clients?: { full_name: string; phone: string } | null };
export type SubscriptionRow = { id: string; client_id: string; order_id: string; package_id: string; status: "pending_payment" | "active" | "paused" | "finished" | "canceled"; start_date: string; delivery_frequency: "daily" | "weekly"; weekly_delivery_day: number | null; total_days: number; consumed_days: number; remaining_days: number; pause_until: string | null; clients?: { full_name: string; delivery_zone: number } | null; packages?: { name: string; size_name: string; price: number } | null; orders?: { order_number: string; status: string; total_price: number } | null };
export type ProductionRow = { id: string; fulfillment_day_id: string; subscription_id: string | null; client_id: string; production_date: string; client_name_snapshot: string; meal_name_snapshot: string; meal_type: string; quantity: number; delivery_zone: number; dietary_notes_snapshot: string | null; status: "pending" | "in_prep" | "approved_done"; source: "calendar" | "custom_override" | "adhoc" | "admin_override" };
export type DeliveryRow = { id: string; subscription_id: string | null; order_id: string; client_id: string; delivery_date: string; zone: number; status: "pending" | "out_for_delivery" | "delivered" | "failed"; cash_expected: number; amount_collected: number; collection_method: string | null; collection_logged_at: string | null; rider_user_id: string | null; clients?: { full_name: string; phone: string; address_text: string | null; location_url: string | null } | null };
export type CancellationRow = { id: string; subscription_id: string; client_id: string; remaining_value: number; consumed_value: number; consumed_penalty: number; delivery_penalty: number; refund_amount: number; status: "requested" | "reviewed" | "approved" | "transferred" | "rejected"; receipt_url: string | null; requested_at: string; clients?: { full_name: string; phone: string } | null };
export type ClientSummaryRow = ClientRow & { total_verified_paid: number; remaining_balance: number; total_orders: number; total_complaints: number; total_cancellations: number };
