/**
 * Browser export helpers were intentionally removed from the authoritative flow.
 * Controlled exports and printable invoices are generated by permission-checked
 * server routes under /api/v1/export and /api/v1/invoices.
 */
export function money(value: string | number) {
  return `${new Intl.NumberFormat("ar-EG", { maximumFractionDigits: 2 }).format(Number(value))} ج`;
}
