"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useERP } from "@/components/erp-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { MealSlot } from "@/lib/erp-types";
import { money } from "@/lib/files";

const slots: MealSlot[] = ["Breakfast", "Lunch", "Dinner", "Snack"];
export default function CatalogPage() {
  const erp = useERP();
  const [mealOpen, setMealOpen] = useState(false); const [packageOpen, setPackageOpen] = useState(false); const [message, setMessage] = useState("");
  const [meal, setMeal] = useState({ name: "", code: "", slot: "Lunch" as MealSlot, regularCost: 0, heroCost: 0, active: true });
  const [pkg, setPkg] = useState({ name: "", code: "", days: 24, priceRegular: 0, priceHero: 0, mealSlots: ["Lunch"] as MealSlot[], active: true });
  async function saveMeal() { const r = await erp.addMeal(meal); setMessage(r.message); if (r.ok) { setMealOpen(false); setMeal({ name: "", code: "", slot: "Lunch", regularCost: 0, heroCost: 0, active: true }); } }
  async function savePackage() { const r = await erp.addPackage(pkg); setMessage(r.message); if (r.ok) { setPackageOpen(false); setPkg({ name: "", code: "", days: 24, priceRegular: 0, priceHero: 0, mealSlots: ["Lunch"], active: true }); } }
  return <AppShell title="المنتجات والباكدجات" subtitle="تعريف الوجبات والأسعار ومكونات كل برنامج">
    {message ? <p className="mb-4 rounded-md bg-[#e8f6ee] p-3 text-sm font-bold text-[#0f603a]">{message}</p> : null}
    <Tabs defaultValue="packages"><TabsList><TabsTrigger value="packages">الباكدجات</TabsTrigger><TabsTrigger value="meals">الوجبات</TabsTrigger></TabsList>
      <TabsContent value="packages"><div className="mb-4 flex justify-end"><Button onClick={() => setPackageOpen(true)}><Plus size={17}/>باكدج جديدة</Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{erp.packages.map((x) => <Card key={x.id}><CardHeader><div className="flex items-start justify-between"><div><CardTitle>{x.name}</CardTitle><p className="mt-1 text-sm text-[#66736b]" dir="ltr">{x.code}</p></div><Badge>{x.days} يوم</Badge></div></CardHeader><CardContent><div className="flex flex-wrap gap-2">{x.mealSlots.map((slot) => <Badge key={slot} variant="blue">{slot}</Badge>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded bg-[#f3f7f4] p-3"><small>Regular</small><b className="mt-1 block">{money(x.priceRegular)}</b></div><div className="rounded bg-[#f3f7f4] p-3"><small>Hero</small><b className="mt-1 block">{money(x.priceHero)}</b></div></div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="meals"><div className="mb-4 flex justify-end"><Button onClick={() => setMealOpen(true)}><Plus size={17}/>وجبة جديدة</Button></div><div className="overflow-x-auto rounded-lg border bg-white"><table className="w-full min-w-[700px] text-sm"><thead className="bg-[#eef4f0] text-right"><tr><th className="p-3">الكود</th><th className="p-3">الوجبة</th><th className="p-3">النوع</th><th className="p-3">تكلفة Regular</th><th className="p-3">تكلفة Hero</th><th className="p-3">الحالة</th></tr></thead><tbody>{erp.meals.map((x) => <tr key={x.id} className="border-t"><td className="p-3 font-bold" dir="ltr">{x.code}</td><td className="p-3 font-bold">{x.name}</td><td className="p-3"><Badge variant="blue">{x.slot}</Badge></td><td className="p-3">{money(x.regularCost)}</td><td className="p-3">{money(x.heroCost)}</td><td className="p-3"><Badge>{x.active ? "نشطة" : "موقوفة"}</Badge></td></tr>)}</tbody></table></div></TabsContent>
    </Tabs>
    <Dialog open={mealOpen} onOpenChange={setMealOpen}><DialogContent><DialogHeader><DialogTitle>إضافة وجبة</DialogTitle></DialogHeader><div className="grid gap-3"><Input placeholder="اسم الوجبة" value={meal.name} onChange={(e) => setMeal({ ...meal, name: e.target.value })}/><Input placeholder="الكود" value={meal.code} onChange={(e) => setMeal({ ...meal, code: e.target.value })} dir="ltr"/><select className="field" value={meal.slot} onChange={(e) => setMeal({ ...meal, slot: e.target.value as MealSlot })}>{slots.map((x) => <option key={x}>{x}</option>)}</select><div className="grid grid-cols-2 gap-3"><Input type="number" placeholder="تكلفة Regular" value={meal.regularCost || ""} onChange={(e) => setMeal({ ...meal, regularCost: Number(e.target.value) })}/><Input type="number" placeholder="تكلفة Hero" value={meal.heroCost || ""} onChange={(e) => setMeal({ ...meal, heroCost: Number(e.target.value) })}/></div><Button onClick={saveMeal} disabled={!meal.name || !meal.code}>حفظ الوجبة</Button></div></DialogContent></Dialog>
    <Dialog open={packageOpen} onOpenChange={setPackageOpen}><DialogContent><DialogHeader><DialogTitle>إضافة باكدج</DialogTitle></DialogHeader><div className="grid gap-3"><Input placeholder="اسم الباكدج" value={pkg.name} onChange={(e) => setPkg({ ...pkg, name: e.target.value })}/><Input placeholder="الكود" value={pkg.code} onChange={(e) => setPkg({ ...pkg, code: e.target.value })} dir="ltr"/><Input type="number" placeholder="عدد الأيام" value={pkg.days} onChange={(e) => setPkg({ ...pkg, days: Number(e.target.value) })}/><div className="grid grid-cols-2 gap-3"><Input type="number" placeholder="سعر Regular" value={pkg.priceRegular || ""} onChange={(e) => setPkg({ ...pkg, priceRegular: Number(e.target.value) })}/><Input type="number" placeholder="سعر Hero" value={pkg.priceHero || ""} onChange={(e) => setPkg({ ...pkg, priceHero: Number(e.target.value) })}/></div><div><label className="mb-2 block text-sm font-bold">الوجبات داخل اليوم</label><div className="grid grid-cols-2 gap-2">{slots.map((slot) => <label key={slot} className="flex items-center gap-2 rounded border p-3 text-sm"><input type="checkbox" checked={pkg.mealSlots.includes(slot)} onChange={(e) => setPkg({ ...pkg, mealSlots: e.target.checked ? [...pkg.mealSlots, slot] : pkg.mealSlots.filter((x) => x !== slot) })}/>{slot}</label>)}</div></div><Button onClick={savePackage} disabled={!pkg.name || !pkg.code || !pkg.mealSlots.length}>حفظ الباكدج</Button></div></DialogContent></Dialog>
  </AppShell>;
}
