begin;

create table public.projects (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid references public.branches(id),
  project_number bigint generated by default as identity,
  name text not null,
  description text,
  owner_user_id uuid references public.profiles(id),
  sponsor_user_id uuid references public.profiles(id),
  department_id uuid references public.departments(id),
  status text not null default 'planned' check (status in ('planned','active','on_hold','at_risk','completed','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','critical')),
  is_strategic boolean not null default false,
  starts_on date,
  due_on date,
  completed_on date,
  progress_percent numeric(5,2) not null default 0 check (progress_percent between 0 and 100),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false,
  unique (organization_id, project_number),
  check (due_on is null or starts_on is null or due_on >= starts_on)
);

create table public.tasks (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid references public.branches(id),
  task_number bigint generated by default as identity,
  project_id uuid references public.projects(id) on delete set null,
  parent_task_id uuid references public.tasks(id) on delete set null,
  title text not null,
  detailed_description text,
  task_type text not null default 'task' check (task_type in ('task','open_task','customer_followup','lead_followup','feedback_request','approval_request','doctor_session','subscription','complaint','payment','refund','internal_action')),
  related_entity_type text,
  related_entity_id uuid,
  department_id uuid references public.departments(id),
  created_by uuid not null references public.profiles(id),
  reviewer_user_id uuid references public.profiles(id),
  priority text not null default 'normal' check (priority in ('low','normal','high','critical')),
  status text not null default 'draft' check (status in ('draft','assigned','open','accepted','in_progress','waiting_for_customer','waiting_for_internal_department','waiting_for_approval','waiting_for_feedback','blocked','response_submitted','in_review','completed','rejected','reopened','cancelled')),
  start_at timestamptz,
  due_at timestamptz,
  open_until_response boolean not null default false,
  expected_response_type text,
  required_action text,
  response_required boolean not null default false,
  evidence_required boolean not null default false,
  reviewer_approval_required boolean not null default false,
  blocker text,
  escalation_level integer not null default 0 check (escalation_level between 0 and 4),
  first_response_at timestamptz,
  completed_at timestamptz,
  approved_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false,
  unique (organization_id, task_number),
  check (due_at is null or start_at is null or due_at >= start_at)
);

create table public.task_assignments (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  assignee_type text not null check (assignee_type in ('user','team','department')),
  assignee_user_id uuid references public.profiles(id),
  assignee_team_id uuid references public.teams(id),
  assignee_department_id uuid references public.departments(id),
  assigned_by uuid not null references public.profiles(id),
  assigned_at timestamptz not null default now(),
  accepted_at timestamptz,
  ended_at timestamptz,
  is_primary boolean not null default true,
  is_demo boolean not null default false,
  check (num_nonnulls(assignee_user_id, assignee_team_id, assignee_department_id) = 1)
);

create table public.task_checklist_items (
  id uuid primary key default extensions.gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  description text not null,
  display_order integer not null default 0,
  is_required boolean not null default true,
  is_completed boolean not null default false,
  completed_by uuid references public.profiles(id),
  completed_at timestamptz,
  is_demo boolean not null default false
);

create table public.task_dependencies (
  task_id uuid not null references public.tasks(id) on delete cascade,
  depends_on_task_id uuid not null references public.tasks(id) on delete cascade,
  dependency_type text not null default 'finish_to_start',
  is_blocking boolean not null default true,
  is_demo boolean not null default false,
  primary key (task_id, depends_on_task_id),
  check (task_id <> depends_on_task_id)
);

create table public.task_activities (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  activity_type text not null,
  actor_user_id uuid references public.profiles(id),
  details jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create table public.task_comments (
  id uuid primary key default extensions.gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  author_user_id uuid not null references public.profiles(id),
  body text not null,
  mentions uuid[] not null default '{}'::uuid[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create table public.task_responses (
  id uuid primary key default extensions.gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  submitted_by uuid not null references public.profiles(id),
  response_type text not null default 'text',
  response_text text not null,
  version integer not null default 1,
  submitted_at timestamptz not null default now(),
  is_official boolean not null default true,
  is_demo boolean not null default false,
  unique (task_id, version)
);

create table public.task_completion_evidence (
  id uuid primary key default extensions.gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  submitted_by uuid not null references public.profiles(id),
  evidence_text text not null,
  submitted_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create table public.task_reviews (
  id uuid primary key default extensions.gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  reviewer_user_id uuid not null references public.profiles(id),
  decision text not null check (decision in ('approved','rejected','changes_requested')),
  feedback text,
  reviewed_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create table public.task_followups (
  id uuid primary key default extensions.gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  contact_method text not null check (contact_method in ('phone','email','whatsapp','meeting','other')),
  contact_at timestamptz not null,
  contact_outcome text,
  customer_response text,
  next_action text,
  next_followup_at timestamptz,
  customer_interest text,
  objection_reason text,
  escalation_required boolean not null default false,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create index projects_scope_idx on public.projects(organization_id, branch_id, status);
create index tasks_scope_idx on public.tasks(organization_id, branch_id, status, due_at);
create index tasks_related_idx on public.tasks(organization_id, related_entity_type, related_entity_id);
create index task_assignments_user_idx on public.task_assignments(assignee_user_id, ended_at, assigned_at);
create index task_activities_timeline_idx on public.task_activities(task_id, occurred_at);

create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();
create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();
create trigger task_comments_set_updated_at before update on public.task_comments for each row execute function public.set_updated_at();
create trigger audit_projects after insert or update or delete on public.projects for each row execute function public.audit_row_change();
create trigger audit_tasks after insert or update or delete on public.tasks for each row execute function public.audit_row_change();
create trigger audit_task_assignments after insert or update or delete on public.task_assignments for each row execute function public.audit_row_change();
create trigger audit_task_reviews after insert or update or delete on public.task_reviews for each row execute function public.audit_row_change();

create or replace function public.enforce_task_completion()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'completed' and old.status is distinct from new.status then
    if new.response_required and not exists (select 1 from public.task_responses r where r.task_id = new.id and r.is_official) then
      raise exception 'official response is required before completion';
    end if;
    if new.evidence_required and not exists (select 1 from public.task_completion_evidence e where e.task_id = new.id) then
      raise exception 'completion evidence is required before completion';
    end if;
    if exists (select 1 from public.task_checklist_items c where c.task_id = new.id and c.is_required and not c.is_completed) then
      raise exception 'required checklist items are incomplete';
    end if;
    if new.reviewer_approval_required and not exists (select 1 from public.task_reviews r where r.task_id = new.id and r.decision = 'approved') then
      raise exception 'reviewer approval is required before completion';
    end if;
    new.completed_at := coalesce(new.completed_at, now());
    if new.reviewer_approval_required then new.approved_at := coalesce(new.approved_at, now()); end if;
  end if;
  return new;
end;
$$;
create trigger tasks_enforce_completion before update of status on public.tasks for each row execute function public.enforce_task_completion();

create or replace function public.record_task_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_type text;
  v_actor uuid;
begin
  v_type := case when tg_op = 'INSERT' then 'task.created' else 'task.updated' end;
  if tg_op = 'UPDATE' and old.status is distinct from new.status then v_type := 'task.status_changed'; end if;
  v_actor := coalesce(auth.uid(), new.created_by);
  insert into public.task_activities(organization_id, task_id, activity_type, actor_user_id, details, is_demo)
  values (new.organization_id, new.id, v_type, v_actor,
    jsonb_build_object('status', new.status, 'previous_status', case when tg_op = 'UPDATE' then old.status else null end, 'due_at', new.due_at),
    new.is_demo);
  perform public.enqueue_domain_event(new.organization_id, new.branch_id, v_type, 'task', new.id,
    jsonb_build_object('title', new.title, 'status', new.status), v_actor,
    v_type || ':' || new.id::text || ':' || extract(epoch from new.updated_at)::bigint::text, new.is_demo);
  return new;
end;
$$;
create trigger tasks_record_activity after insert or update of status, due_at, reviewer_user_id on public.tasks for each row execute function public.record_task_activity();

create or replace function public.escalate_overdue_tasks(p_now timestamptz default now())
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  with escalated as (
    update public.tasks
    set escalation_level = least(escalation_level + 1, 4), updated_at = now()
    where due_at < p_now
      and status not in ('completed','cancelled','rejected')
      and escalation_level < 4
    returning id, organization_id, branch_id, title, escalation_level, is_demo
  ), events as (
    insert into public.domain_events(organization_id, branch_id, event_type, aggregate_type, aggregate_id, payload, idempotency_key, is_demo)
    select organization_id, branch_id, 'task.overdue', 'task', id,
      jsonb_build_object('title', title, 'escalation_level', escalation_level),
      'task.overdue:' || id::text || ':' || escalation_level::text, is_demo
    from escalated
    on conflict (organization_id, idempotency_key) do nothing
    returning 1
  ) select count(*) into v_count from escalated;
  return v_count;
end;
$$;

alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.task_assignments enable row level security;
alter table public.task_checklist_items enable row level security;
alter table public.task_dependencies enable row level security;
alter table public.task_activities enable row level security;
alter table public.task_comments enable row level security;
alter table public.task_responses enable row level security;
alter table public.task_completion_evidence enable row level security;
alter table public.task_reviews enable row level security;
alter table public.task_followups enable row level security;

create policy projects_select_scope on public.projects for select to authenticated
using (public.is_organization_member(organization_id) and (branch_id is null or public.can_access_branch(organization_id, branch_id)) and (public.has_permission('projects.view', organization_id) or owner_user_id = auth.uid()));
create policy projects_manage_scope on public.projects for all to authenticated
using (public.has_permission('projects.manage', organization_id) and (branch_id is null or public.can_access_branch(organization_id, branch_id)))
with check (public.has_permission('projects.manage', organization_id) and (branch_id is null or public.can_access_branch(organization_id, branch_id)));
create policy tasks_select_scope on public.tasks for select to authenticated
using (public.is_organization_member(organization_id) and (branch_id is null or public.can_access_branch(organization_id, branch_id)) and (
  public.has_permission('tasks.view_all', organization_id) or public.has_permission('tasks.view_team', organization_id)
  or created_by = auth.uid() or reviewer_user_id = auth.uid()
  or exists (select 1 from public.task_assignments a where a.task_id = id and a.assignee_user_id = auth.uid() and a.ended_at is null)
));
create policy tasks_create_scope on public.tasks for insert to authenticated
with check (created_by = auth.uid() and public.has_permission('tasks.create', organization_id) and (branch_id is null or public.can_access_branch(organization_id, branch_id)));
create policy tasks_update_scope on public.tasks for update to authenticated
using (public.has_permission('tasks.assign', organization_id) or reviewer_user_id = auth.uid() or exists (select 1 from public.task_assignments a where a.task_id = id and a.assignee_user_id = auth.uid() and a.ended_at is null))
with check (public.is_organization_member(organization_id));

create policy task_children_select on public.task_assignments for select to authenticated using (exists (select 1 from public.tasks t where t.id = task_id));
create policy task_assignments_manage on public.task_assignments for all to authenticated using (public.has_permission('tasks.assign', organization_id)) with check (public.has_permission('tasks.assign', organization_id) and assigned_by = auth.uid());
create policy checklist_scope on public.task_checklist_items for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (exists (select 1 from public.tasks t where t.id = task_id));
create policy dependencies_scope on public.task_dependencies for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (exists (select 1 from public.tasks t where t.id = task_id));
create policy activities_select on public.task_activities for select to authenticated using (exists (select 1 from public.tasks t where t.id = task_id));
create policy comments_scope on public.task_comments for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (author_user_id = auth.uid() and exists (select 1 from public.tasks t where t.id = task_id));
create policy responses_scope on public.task_responses for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (submitted_by = auth.uid() and exists (select 1 from public.tasks t where t.id = task_id));
create policy evidence_scope on public.task_completion_evidence for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (submitted_by = auth.uid() and exists (select 1 from public.tasks t where t.id = task_id));
create policy reviews_scope on public.task_reviews for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (reviewer_user_id = auth.uid() and public.has_permission('tasks.review', (select organization_id from public.tasks where id = task_id)));
create policy followups_scope on public.task_followups for all to authenticated using (exists (select 1 from public.tasks t where t.id = task_id)) with check (created_by = auth.uid() and exists (select 1 from public.tasks t where t.id = task_id));

insert into public.role_permissions(role_id, permission_id)
select r.id, p.id from public.roles r join public.permissions p on p.code in ('tasks.create','tasks.assign','tasks.view_own','tasks.view_team','tasks.view_all','tasks.respond','tasks.review','tasks.reopen')
where r.code = 'project_manager' on conflict do nothing;
insert into public.role_permissions(role_id, permission_id)
select r.id, p.id from public.roles r join public.permissions p on p.code in ('tasks.create','tasks.view_own','tasks.respond')
where r.code = 'task_assignee' on conflict do nothing;

insert into public.schema_versions(version, name) values (5, 'projects_tasks_followups');
commit;
