begin;

insert into public.permissions(code,name,module,description,is_sensitive) values
('leads.view','View leads','CRM','View leads in branch scope',false),
('leads.manage','Manage leads','CRM','Create and update leads',false),
('leads.assign','Assign leads','CRM','Assign and reassign leads',true),
('leads.convert','Convert leads','CRM','Convert a qualified lead to customer',false),
('customers.view','View customers','CRM','View customer profiles in branch scope',false),
('customers.manage','Manage customers','CRM','Create and update customer records',false),
('customers.view_sensitive','View sensitive customer data','CRM','View allergy and restricted customer notes',true),
('complaints.view','View complaints','Customer Service','View customer complaints',false),
('complaints.manage','Manage complaints','Customer Service','Create, investigate and resolve complaints',false)
on conflict (code) do nothing;

insert into public.role_permissions(role_id, permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('leads.view','leads.manage','leads.assign','leads.convert','customers.view','customers.manage','complaints.view')
where r.code in ('sales_manager','sales_team_leader') on conflict do nothing;
insert into public.role_permissions(role_id, permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('leads.view','leads.manage','leads.convert','customers.view','customers.manage')
where r.code = 'sales_representative' on conflict do nothing;
insert into public.role_permissions(role_id, permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('customers.view','customers.manage','customers.view_sensitive','complaints.view','complaints.manage')
where r.code in ('customer_service','operations_manager') on conflict do nothing;
insert into public.role_permissions(role_id, permission_id)
select r.id,p.id from public.roles r cross join public.permissions p where r.code='ceo_super_admin' on conflict do nothing;

create table public.staff_directory (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid references public.branches(id),
  profile_id uuid references public.profiles(id),
  employee_code text not null,
  display_name text not null,
  role_label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  is_demo boolean not null default false,
  unique (organization_id, employee_code)
);

create table public.leads (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id),
  lead_number bigint generated by default as identity,
  full_name text not null,
  mobile text,
  email extensions.citext,
  source text,
  campaign text,
  status text not null default 'new' check (status in ('new','assigned','contacted','qualified','proposal','won','lost','converted')),
  temperature text not null default 'warm' check (temperature in ('cold','warm','hot')),
  assigned_user_id uuid references public.profiles(id),
  assigned_staff_id uuid references public.staff_directory(id),
  next_followup_at timestamptz,
  loss_reason text,
  converted_customer_id uuid,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false,
  unique (organization_id, lead_number)
);

create table public.customers (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  home_branch_id uuid references public.branches(id),
  customer_number bigint generated by default as identity,
  full_name text not null,
  mobile text,
  email extensions.citext,
  gender text,
  birth_date date,
  status text not null default 'active' check (status in ('active','inactive','blocked')),
  source_lead_id uuid references public.leads(id),
  owner_user_id uuid references public.profiles(id),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false,
  unique (organization_id, customer_number)
);
alter table public.leads add constraint leads_converted_customer_fk foreign key (converted_customer_id) references public.customers(id) deferrable initially deferred;

create unique index customers_org_mobile_uidx on public.customers(organization_id, mobile) where mobile is not null and not is_demo;
create index leads_scope_idx on public.leads(organization_id, branch_id, status, next_followup_at);
create index customers_scope_idx on public.customers(organization_id, home_branch_id, status);

create table public.customer_addresses (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  label text not null,
  address_line text not null,
  area text,
  city text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  delivery_notes text,
  is_primary boolean not null default false,
  is_demo boolean not null default false
);

create table public.customer_preferences (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  preference_type text not null check (preference_type in ('like','dislike','restriction','goal','general')),
  value text not null,
  is_permanent boolean not null default true,
  valid_until date,
  visibility text not null default 'operations' check (visibility in ('all_staff','operations','medical')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create table public.customer_allergies (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  allergen text not null,
  severity text not null default 'unknown' check (severity in ('unknown','mild','moderate','severe')),
  notes text,
  verified_by uuid references public.profiles(id),
  verified_at timestamptz,
  is_demo boolean not null default false
);

create table public.customer_notes (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  note_type text not null default 'general' check (note_type in ('general','sales','operations','medical','finance')),
  body text not null,
  visibility text not null default 'internal' check (visibility in ('internal','restricted','customer_visible')),
  author_user_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  is_demo boolean not null default false
);

create table public.complaint_categories (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null,
  name text not null,
  default_sla_hours integer not null default 24 check (default_sla_hours > 0),
  is_active boolean not null default true,
  is_demo boolean not null default false,
  unique (organization_id, code)
);

create table public.complaints (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid references public.branches(id),
  complaint_number bigint generated by default as identity,
  customer_id uuid not null references public.customers(id),
  category_id uuid references public.complaint_categories(id),
  reason text not null,
  details text,
  severity text not null default 'normal' check (severity in ('low','normal','high','critical')),
  status text not null default 'open' check (status in ('open','investigating','waiting_customer','resolved','closed','reopened')),
  owner_user_id uuid references public.profiles(id),
  due_at timestamptz,
  root_cause text,
  corrective_action text,
  satisfaction_score integer check (satisfaction_score between 1 and 5),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz,
  updated_at timestamptz not null default now(),
  is_demo boolean not null default false,
  unique (organization_id, complaint_number)
);

create table public.cancellation_reasons (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null,
  name text not null,
  category text not null,
  is_active boolean not null default true,
  is_demo boolean not null default false,
  unique (organization_id, code)
);

create table public.customer_timeline (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  event_type text not null,
  title text not null,
  details jsonb not null default '{}'::jsonb,
  related_type text,
  related_id uuid,
  actor_user_id uuid references public.profiles(id),
  occurred_at timestamptz not null default now(),
  is_demo boolean not null default false
);
create index customer_timeline_idx on public.customer_timeline(customer_id, occurred_at desc);
create index complaints_scope_idx on public.complaints(organization_id, branch_id, status, due_at);

create trigger leads_set_updated_at before update on public.leads for each row execute function public.set_updated_at();
create trigger customers_set_updated_at before update on public.customers for each row execute function public.set_updated_at();
create trigger complaints_set_updated_at before update on public.complaints for each row execute function public.set_updated_at();
create trigger audit_leads after insert or update or delete on public.leads for each row execute function public.audit_row_change();
create trigger audit_customers after insert or update or delete on public.customers for each row execute function public.audit_row_change();
create trigger audit_complaints after insert or update or delete on public.complaints for each row execute function public.audit_row_change();

create or replace function public.convert_lead_to_customer(p_lead_id uuid, p_actor_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare v_lead public.leads; v_customer_id uuid;
begin
  select * into v_lead from public.leads where id = p_lead_id for update;
  if v_lead.id is null or v_lead.status in ('converted','lost') then raise exception 'lead is not convertible'; end if;
  if p_actor_user_id is distinct from auth.uid() and auth.role() <> 'service_role' then raise exception 'actor mismatch'; end if;
  if auth.uid() is not null and not public.has_permission('leads.convert', v_lead.organization_id) then raise exception 'leads.convert is required'; end if;
  insert into public.customers(organization_id,home_branch_id,full_name,mobile,email,source_lead_id,owner_user_id,created_by,is_demo)
  values(v_lead.organization_id,v_lead.branch_id,v_lead.full_name,v_lead.mobile,v_lead.email,v_lead.id,v_lead.assigned_user_id,p_actor_user_id,v_lead.is_demo)
  returning id into v_customer_id;
  update public.leads set status='converted',converted_customer_id=v_customer_id,updated_at=now() where id=v_lead.id;
  insert into public.customer_timeline(organization_id,customer_id,event_type,title,related_type,related_id,actor_user_id,is_demo)
  values(v_lead.organization_id,v_customer_id,'lead.converted','Converted from lead','lead',v_lead.id,p_actor_user_id,v_lead.is_demo);
  perform public.enqueue_domain_event(v_lead.organization_id,v_lead.branch_id,'lead.converted','customer',v_customer_id,jsonb_build_object('lead_id',v_lead.id),p_actor_user_id,'lead.converted:'||v_lead.id::text,v_lead.is_demo);
  return v_customer_id;
end;
$$;

alter table public.staff_directory enable row level security;
alter table public.leads enable row level security;
alter table public.customers enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.customer_preferences enable row level security;
alter table public.customer_allergies enable row level security;
alter table public.customer_notes enable row level security;
alter table public.complaint_categories enable row level security;
alter table public.complaints enable row level security;
alter table public.cancellation_reasons enable row level security;
alter table public.customer_timeline enable row level security;

create policy staff_scope on public.staff_directory for select to authenticated using (public.is_organization_member(organization_id) and (branch_id is null or public.can_access_branch(organization_id,branch_id)));
create policy leads_select_scope on public.leads for select to authenticated using (public.has_permission('leads.view',organization_id) and public.can_access_branch(organization_id,branch_id));
create policy leads_manage_scope on public.leads for all to authenticated using (public.has_permission('leads.manage',organization_id) and public.can_access_branch(organization_id,branch_id)) with check (public.has_permission('leads.manage',organization_id) and public.can_access_branch(organization_id,branch_id));
create policy customers_select_scope on public.customers for select to authenticated using (public.has_permission('customers.view',organization_id) and (home_branch_id is null or public.can_access_branch(organization_id,home_branch_id)));
create policy customers_manage_scope on public.customers for all to authenticated using (public.has_permission('customers.manage',organization_id) and (home_branch_id is null or public.can_access_branch(organization_id,home_branch_id))) with check (public.has_permission('customers.manage',organization_id));
create policy customer_addresses_scope on public.customer_addresses for all to authenticated using (exists(select 1 from public.customers c where c.id=customer_id)) with check (exists(select 1 from public.customers c where c.id=customer_id));
create policy customer_preferences_scope on public.customer_preferences for all to authenticated using (exists(select 1 from public.customers c where c.id=customer_id) and (visibility <> 'medical' or public.has_permission('customers.view_sensitive',(select organization_id from public.customers where id=customer_id)))) with check (exists(select 1 from public.customers c where c.id=customer_id));
create policy customer_allergies_scope on public.customer_allergies for all to authenticated using (public.has_permission('customers.view_sensitive',(select organization_id from public.customers where id=customer_id))) with check (public.has_permission('customers.view_sensitive',(select organization_id from public.customers where id=customer_id)));
create policy customer_notes_scope on public.customer_notes for all to authenticated using (exists(select 1 from public.customers c where c.id=customer_id) and (note_type <> 'medical' or public.has_permission('customers.view_sensitive',(select organization_id from public.customers where id=customer_id)))) with check (author_user_id=auth.uid() and exists(select 1 from public.customers c where c.id=customer_id));
create policy complaint_categories_scope on public.complaint_categories for select to authenticated using (public.is_organization_member(organization_id));
create policy complaints_select_scope on public.complaints for select to authenticated using (public.has_permission('complaints.view',organization_id) and (branch_id is null or public.can_access_branch(organization_id,branch_id)));
create policy complaints_manage_scope on public.complaints for all to authenticated using (public.has_permission('complaints.manage',organization_id)) with check (public.has_permission('complaints.manage',organization_id) and created_by=auth.uid());
create policy cancellation_reasons_scope on public.cancellation_reasons for select to authenticated using (public.is_organization_member(organization_id));
create policy timeline_scope on public.customer_timeline for select to authenticated using (public.has_permission('customers.view',organization_id));

insert into public.schema_versions(version,name) values(6,'crm_customers_complaints');
commit;
