begin;

insert into public.permissions(code,name,module,description,is_sensitive) values
('catalog.view','View catalog','Sales','View packages and price versions',false),
('catalog.manage','Manage catalog','Sales','Create versioned packages and pricing',true),
('sales.quote','Create quotations','Sales','Create and issue quotations',false),
('sales.invoice','Create invoices','Sales','Create invoices from accepted quotations',false),
('payments.submit','Submit payment proof','Finance','Submit customer payment proof for review',false),
('payments.review','Review payment submissions','Finance','Review payment proofs',true),
('payments.confirm','Confirm cash collection','Finance','Create confirmed cash transactions',true),
('refunds.request','Request refunds','Finance','Request a governed customer refund',false),
('refunds.approve','Approve refunds','Finance','Approve refunds under maker-checker',true),
('subscriptions.view','View subscriptions','Subscriptions','View subscriptions in branch scope',false),
('subscriptions.manage','Manage subscriptions','Subscriptions','Activate, freeze and cancel subscriptions',true),
('service.confirm_delivery','Confirm service delivery','Subscriptions','Confirm delivered service days',true),
('revenue.view','View revenue subledger','Finance','View deferred and recognized revenue',true)
on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('catalog.view','sales.quote','sales.invoice','payments.submit','subscriptions.view') where r.code in ('sales_manager','sales_team_leader','sales_representative') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('catalog.view','payments.review','payments.confirm','refunds.approve','subscriptions.view','revenue.view') where r.code in ('finance_manager','finance_accountant') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in ('subscriptions.view','subscriptions.manage','service.confirm_delivery') where r.code='operations_manager' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.code='ceo_super_admin' on conflict do nothing;

create table public.packages (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null, name text not null, description text, status text not null default 'active' check(status in('active','inactive')),
  created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_demo boolean not null default false,
  unique(organization_id,code)
);
create table public.package_versions (
  id uuid primary key default extensions.gen_random_uuid(), package_id uuid not null references public.packages(id) on delete cascade,
  version_number integer not null, effective_from date not null, effective_to date, currency char(3) not null default 'EGP', price numeric(18,2) not null check(price>=0),
  service_days integer not null check(service_days>0), meals_per_day integer not null default 1 check(meals_per_day>0),
  freeze_policy jsonb not null default '{}'::jsonb, cancellation_policy jsonb not null default '{}'::jsonb, recognition_policy jsonb not null default '{"method":"per_delivered_day"}'::jsonb,
  status text not null default 'active' check(status in('draft','active','expired')), created_by uuid references public.profiles(id), created_at timestamptz not null default now(), is_demo boolean not null default false,
  unique(package_id,version_number), check(effective_to is null or effective_to>=effective_from)
);
create table public.discount_limits (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  role_id uuid references public.roles(id), user_id uuid references public.profiles(id), maximum_percent numeric(5,2) not null check(maximum_percent between 0 and 100),
  effective_from date not null, effective_to date, approved_by uuid references public.profiles(id), is_demo boolean not null default false,
  check(num_nonnulls(role_id,user_id)=1)
);

create table public.quotations (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id), quotation_number bigint generated by default as identity, customer_id uuid not null references public.customers(id),
  status text not null default 'draft' check(status in('draft','issued','accepted','rejected','expired','converted')),
  currency char(3) not null default 'EGP', subtotal numeric(18,2) not null default 0, discount_amount numeric(18,2) not null default 0,
  total_amount numeric(18,2) generated always as (subtotal-discount_amount) stored, valid_until date, notes text,
  created_by uuid not null references public.profiles(id), accepted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_demo boolean not null default false,
  unique(organization_id,quotation_number), check(discount_amount>=0 and discount_amount<=subtotal)
);
create table public.quotation_lines (
  id uuid primary key default extensions.gen_random_uuid(), quotation_id uuid not null references public.quotations(id) on delete cascade,
  package_version_id uuid references public.package_versions(id), description text not null, quantity numeric(12,2) not null default 1 check(quantity>0),
  unit_price numeric(18,2) not null check(unit_price>=0), discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100),
  line_total numeric(18,2) generated always as (quantity*unit_price*(1-discount_percent/100)) stored, price_snapshot jsonb not null default '{}'::jsonb, is_demo boolean not null default false
);
create table public.invoices (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id), invoice_number bigint generated by default as identity, customer_id uuid not null references public.customers(id), quotation_id uuid references public.quotations(id),
  status text not null default 'issued' check(status in('draft','issued','partially_paid','paid','cancelled','refunded')),
  currency char(3) not null default 'EGP', total_amount numeric(18,2) not null check(total_amount>=0), confirmed_paid_amount numeric(18,2) not null default 0 check(confirmed_paid_amount>=0),
  issued_at timestamptz not null default now(), due_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_demo boolean not null default false,
  unique(organization_id,invoice_number), check(confirmed_paid_amount<=total_amount)
);
create table public.invoice_lines (
  id uuid primary key default extensions.gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade,
  package_version_id uuid references public.package_versions(id), description text not null, quantity numeric(12,2) not null default 1, unit_price numeric(18,2) not null,
  line_total numeric(18,2) not null, source_snapshot jsonb not null default '{}'::jsonb, is_demo boolean not null default false
);

create table public.payment_submissions (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id), submission_number bigint generated by default as identity, customer_id uuid not null references public.customers(id), invoice_id uuid references public.invoices(id),
  claimed_amount numeric(18,2) not null check(claimed_amount>0), currency char(3) not null default 'EGP', payment_method text not null,
  proof_reference text not null, external_reference text, status text not null default 'pending' check(status in('pending','under_review','confirmed','partially_confirmed','rejected','duplicate')),
  submitted_by uuid not null references public.profiles(id), submitted_at timestamptz not null default now(), reviewed_by uuid references public.profiles(id), reviewed_at timestamptz,
  confirmed_amount numeric(18,2), rejection_reason text, is_demo boolean not null default false,
  unique(organization_id,submission_number), check(reviewed_by is null or reviewed_by<>submitted_by)
);
create unique index payment_submission_reference_uidx on public.payment_submissions(organization_id,external_reference) where external_reference is not null;
create table public.payment_transactions (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id), customer_id uuid not null references public.customers(id), submission_id uuid references public.payment_submissions(id),
  transaction_type text not null check(transaction_type in('collection','refund','reversal','adjustment')), amount numeric(18,2) not null check(amount<>0), currency char(3) not null default 'EGP',
  confirmed_by uuid not null references public.profiles(id), confirmed_at timestamptz not null default now(), reversal_of_id uuid references public.payment_transactions(id),
  idempotency_key text not null, is_demo boolean not null default false, unique(organization_id,idempotency_key)
);
create table public.payment_allocations (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  transaction_id uuid not null references public.payment_transactions(id), invoice_id uuid references public.invoices(id), subscription_id uuid,
  allocation_type text not null check(allocation_type in('invoice','subscription','customer_credit','advance','suspense')),
  amount numeric(18,2) not null check(amount>0), allocated_by uuid not null references public.profiles(id), allocated_at timestamptz not null default now(), reversed_at timestamptz, is_demo boolean not null default false
);

create table public.subscriptions (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id), subscription_number bigint generated by default as identity, customer_id uuid not null references public.customers(id), invoice_id uuid not null references public.invoices(id),
  package_version_id uuid not null references public.package_versions(id), status text not null default 'pending_payment' check(status in('pending_payment','active','frozen','completed','cancelled')),
  starts_on date, ends_on date, purchased_service_days integer not null, delivered_service_days integer not null default 0,
  contract_value numeric(18,2) not null, deferred_balance numeric(18,2) not null default 0, recognized_revenue numeric(18,2) not null default 0,
  activated_by uuid references public.profiles(id), activated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_demo boolean not null default false,
  unique(organization_id,subscription_number), check(delivered_service_days between 0 and purchased_service_days), check(deferred_balance>=0 and recognized_revenue>=0)
);
alter table public.payment_allocations add constraint payment_allocations_subscription_fk foreign key(subscription_id) references public.subscriptions(id);
create table public.subscription_freezes (
  id uuid primary key default extensions.gen_random_uuid(), subscription_id uuid not null references public.subscriptions(id), starts_on date not null, ends_on date not null,
  reason text not null, status text not null default 'approved' check(status in('requested','approved','rejected','ended')), approved_by uuid references public.profiles(id), is_demo boolean not null default false,
  check(ends_on>=starts_on)
);
create table public.subscription_cancellations (
  id uuid primary key default extensions.gen_random_uuid(), subscription_id uuid not null references public.subscriptions(id), reason_id uuid references public.cancellation_reasons(id), details text,
  requested_by uuid not null references public.profiles(id), requested_at timestamptz not null default now(), approved_by uuid references public.profiles(id), approved_at timestamptz,
  status text not null default 'requested' check(status in('requested','approved','rejected','completed')), is_demo boolean not null default false,
  check(approved_by is null or approved_by<>requested_by)
);
create table public.refunds (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null references public.branches(id), customer_id uuid not null references public.customers(id), subscription_id uuid references public.subscriptions(id),
  amount numeric(18,2) not null check(amount>0), reason text not null, status text not null default 'requested' check(status in('requested','under_review','approved','paid','rejected','cancelled')),
  requested_by uuid not null references public.profiles(id), approved_by uuid references public.profiles(id), paid_by uuid references public.profiles(id), payment_proof_reference text,
  requested_at timestamptz not null default now(), approved_at timestamptz, paid_at timestamptz, is_demo boolean not null default false,
  check(approved_by is null or approved_by<>requested_by)
);
create table public.planned_service_days (
  id uuid primary key default extensions.gen_random_uuid(), subscription_id uuid not null references public.subscriptions(id), service_date date not null,
  status text not null default 'planned' check(status in('planned','frozen','cancelled','not_delivered','exception','delivered_pending_confirmation')),
  branch_id uuid references public.branches(id), is_demo boolean not null default false, unique(subscription_id,service_date)
);
create table public.service_delivery_confirmations (
  id uuid primary key default extensions.gen_random_uuid(), planned_service_day_id uuid not null references public.planned_service_days(id), subscription_id uuid not null references public.subscriptions(id),
  status text not null check(status in('confirmed_delivered','reversed')), confirmed_by uuid not null references public.profiles(id), confirmed_at timestamptz not null default now(),
  reversal_of_id uuid references public.service_delivery_confirmations(id), reversal_reason text, is_demo boolean not null default false
);
create unique index one_active_delivery_confirmation on public.service_delivery_confirmations(planned_service_day_id) where status='confirmed_delivered';
create table public.revenue_entries (
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  subscription_id uuid not null references public.subscriptions(id), delivery_confirmation_id uuid references public.service_delivery_confirmations(id),
  entry_type text not null check(entry_type in('recognition','reversal','adjustment')), amount numeric(18,2) not null check(amount<>0), entry_date date not null,
  created_by uuid not null references public.profiles(id), idempotency_key text not null, is_demo boolean not null default false,
  unique(organization_id,idempotency_key)
);

create index quotations_scope_idx on public.quotations(organization_id,branch_id,status,created_at desc);
create index invoices_scope_idx on public.invoices(organization_id,branch_id,status,issued_at desc);
create index payment_submissions_queue_idx on public.payment_submissions(organization_id,status,submitted_at);
create index payment_transactions_customer_idx on public.payment_transactions(customer_id,confirmed_at desc);
create index subscriptions_ops_idx on public.subscriptions(organization_id,branch_id,status,ends_on);
create index planned_service_days_daily_idx on public.planned_service_days(service_date,branch_id,status);

create trigger packages_set_updated_at before update on public.packages for each row execute function public.set_updated_at();
create trigger quotations_set_updated_at before update on public.quotations for each row execute function public.set_updated_at();
create trigger invoices_set_updated_at before update on public.invoices for each row execute function public.set_updated_at();
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();
create trigger audit_quotations after insert or update or delete on public.quotations for each row execute function public.audit_row_change();
create trigger audit_invoices after insert or update or delete on public.invoices for each row execute function public.audit_row_change();
create trigger audit_payment_submissions after insert or update or delete on public.payment_submissions for each row execute function public.audit_row_change();
create trigger audit_payment_transactions after insert or update or delete on public.payment_transactions for each row execute function public.audit_row_change();
create trigger audit_subscriptions after insert or update or delete on public.subscriptions for each row execute function public.audit_row_change();
create trigger audit_refunds after insert or update or delete on public.refunds for each row execute function public.audit_row_change();
create trigger audit_delivery_confirmations after insert or update or delete on public.service_delivery_confirmations for each row execute function public.audit_row_change();

create or replace function public.confirm_payment_submission(p_submission_id uuid,p_confirmed_amount numeric,p_actor_user_id uuid,p_idempotency_key text)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_submission public.payment_submissions; v_transaction_id uuid; v_invoice public.invoices;
begin
  select * into v_submission from public.payment_submissions where id=p_submission_id for update;
  if v_submission.id is null or v_submission.status not in('pending','under_review') then raise exception 'payment submission is not confirmable'; end if;
  if p_actor_user_id=v_submission.submitted_by then raise exception 'maker cannot confirm own payment'; end if;
  if auth.uid() is not null and (p_actor_user_id<>auth.uid() or not public.has_permission('payments.confirm',v_submission.organization_id)) then raise exception 'payments.confirm is required'; end if;
  if p_confirmed_amount<=0 or p_confirmed_amount>v_submission.claimed_amount then raise exception 'invalid confirmed amount'; end if;
  insert into public.payment_transactions(organization_id,branch_id,customer_id,submission_id,transaction_type,amount,currency,confirmed_by,idempotency_key,is_demo)
  values(v_submission.organization_id,v_submission.branch_id,v_submission.customer_id,v_submission.id,'collection',p_confirmed_amount,v_submission.currency,p_actor_user_id,p_idempotency_key,v_submission.is_demo)
  on conflict(organization_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into v_transaction_id;
  update public.payment_submissions set status=case when p_confirmed_amount=v_submission.claimed_amount then 'confirmed' else 'partially_confirmed' end,
    confirmed_amount=p_confirmed_amount,reviewed_by=p_actor_user_id,reviewed_at=now() where id=v_submission.id;
  if v_submission.invoice_id is not null then
    select * into v_invoice from public.invoices where id=v_submission.invoice_id for update;
    update public.invoices set confirmed_paid_amount=least(total_amount,confirmed_paid_amount+p_confirmed_amount),
      status=case when confirmed_paid_amount+p_confirmed_amount>=total_amount then 'paid' else 'partially_paid' end where id=v_invoice.id;
    insert into public.payment_allocations(organization_id,transaction_id,invoice_id,allocation_type,amount,allocated_by,is_demo)
    values(v_submission.organization_id,v_transaction_id,v_invoice.id,'invoice',least(p_confirmed_amount,v_invoice.total_amount-v_invoice.confirmed_paid_amount),p_actor_user_id,v_submission.is_demo);
  end if;
  perform public.enqueue_domain_event(v_submission.organization_id,v_submission.branch_id,'payment.confirmed','payment_transaction',v_transaction_id,jsonb_build_object('amount',p_confirmed_amount,'invoice_id',v_submission.invoice_id),p_actor_user_id,'payment.confirmed:'||v_transaction_id::text,v_submission.is_demo);
  return v_transaction_id;
end; $$;

create or replace function public.activate_subscription(p_subscription_id uuid,p_actor_user_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare v_subscription public.subscriptions; v_invoice public.invoices;
begin
  select * into v_subscription from public.subscriptions where id=p_subscription_id for update;
  select * into v_invoice from public.invoices where id=v_subscription.invoice_id;
  if v_invoice.status not in('paid','partially_paid') or v_invoice.confirmed_paid_amount<=0 then raise exception 'confirmed payment is required'; end if;
  if auth.uid() is not null and not public.has_permission('subscriptions.manage',v_subscription.organization_id) then raise exception 'subscriptions.manage is required'; end if;
  update public.subscriptions set status='active',activated_by=p_actor_user_id,activated_at=now(),deferred_balance=least(contract_value,v_invoice.confirmed_paid_amount),updated_at=now() where id=p_subscription_id;
  perform public.enqueue_domain_event(v_subscription.organization_id,v_subscription.branch_id,'subscription.activated','subscription',v_subscription.id,'{}'::jsonb,p_actor_user_id,'subscription.activated:'||v_subscription.id::text,v_subscription.is_demo);
end; $$;

create or replace function public.confirm_service_delivery(p_planned_day_id uuid,p_actor_user_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_day public.planned_service_days; v_subscription public.subscriptions; v_confirmation_id uuid; v_amount numeric(18,2);
begin
  select * into v_day from public.planned_service_days where id=p_planned_day_id for update;
  select * into v_subscription from public.subscriptions where id=v_day.subscription_id for update;
  if v_day.status not in('planned','delivered_pending_confirmation') or v_subscription.status<>'active' then raise exception 'service day is not deliverable'; end if;
  if auth.uid() is not null and not public.has_permission('service.confirm_delivery',v_subscription.organization_id) then raise exception 'service.confirm_delivery is required'; end if;
  insert into public.service_delivery_confirmations(planned_service_day_id,subscription_id,status,confirmed_by,is_demo)
  values(v_day.id,v_subscription.id,'confirmed_delivered',p_actor_user_id,v_day.is_demo) returning id into v_confirmation_id;
  v_amount:=round(v_subscription.contract_value/v_subscription.purchased_service_days,2);
  insert into public.revenue_entries(organization_id,subscription_id,delivery_confirmation_id,entry_type,amount,entry_date,created_by,idempotency_key,is_demo)
  values(v_subscription.organization_id,v_subscription.id,v_confirmation_id,'recognition',v_amount,v_day.service_date,p_actor_user_id,'delivery:'||v_day.id::text,v_day.is_demo);
  update public.planned_service_days set status='delivered_pending_confirmation' where id=v_day.id;
  update public.subscriptions set delivered_service_days=delivered_service_days+1,recognized_revenue=recognized_revenue+v_amount,deferred_balance=greatest(0,deferred_balance-v_amount),updated_at=now() where id=v_subscription.id;
  return v_confirmation_id;
end; $$;

create view public.subscriber_operations_v with(security_invoker=true) as
select s.id,s.organization_id,s.branch_id,s.subscription_number,s.status,s.starts_on,s.ends_on,s.purchased_service_days,s.delivered_service_days,
  s.purchased_service_days-s.delivered_service_days as remaining_service_days,s.deferred_balance,c.full_name as customer_name,p.name as package_name
from public.subscriptions s join public.customers c on c.id=s.customer_id join public.package_versions pv on pv.id=s.package_version_id join public.packages p on p.id=pv.package_id;
create view public.daily_subscriber_list_v with(security_invoker=true) as
select d.id,d.service_date,d.status,d.branch_id,s.subscription_number,c.full_name as customer_name,p.name as package_name
from public.planned_service_days d join public.subscriptions s on s.id=d.subscription_id join public.customers c on c.id=s.customer_id join public.package_versions pv on pv.id=s.package_version_id join public.packages p on p.id=pv.package_id;

do $$ declare t text; begin foreach t in array array['packages','package_versions','discount_limits','quotations','quotation_lines','invoices','invoice_lines','payment_submissions','payment_transactions','payment_allocations','subscriptions','subscription_freezes','subscription_cancellations','refunds','planned_service_days','service_delivery_confirmations','revenue_entries'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy package_select on public.packages for select to authenticated using(public.has_permission('catalog.view',organization_id));
create policy package_manage on public.packages for all to authenticated using(public.has_permission('catalog.manage',organization_id)) with check(public.has_permission('catalog.manage',organization_id));
create policy package_versions_scope on public.package_versions for select to authenticated using(exists(select 1 from public.packages p where p.id=package_id));
create policy quotations_scope on public.quotations for all to authenticated using(public.has_permission('sales.quote',organization_id) and public.can_access_branch(organization_id,branch_id)) with check(public.has_permission('sales.quote',organization_id) and created_by=auth.uid());
create policy quotation_lines_scope on public.quotation_lines for all to authenticated using(exists(select 1 from public.quotations q where q.id=quotation_id)) with check(exists(select 1 from public.quotations q where q.id=quotation_id));
create policy invoices_scope on public.invoices for select to authenticated using((public.has_permission('sales.invoice',organization_id) or public.has_permission('payments.review',organization_id)) and public.can_access_branch(organization_id,branch_id));
create policy invoice_lines_scope on public.invoice_lines for select to authenticated using(exists(select 1 from public.invoices i where i.id=invoice_id));
create policy payment_submissions_scope on public.payment_submissions for select to authenticated using((submitted_by=auth.uid() or public.has_permission('payments.review',organization_id)) and public.can_access_branch(organization_id,branch_id));
create policy payment_submissions_insert on public.payment_submissions for insert to authenticated with check(submitted_by=auth.uid() and public.has_permission('payments.submit',organization_id));
create policy payment_transactions_scope on public.payment_transactions for select to authenticated using(public.has_permission('payments.review',organization_id) and public.can_access_branch(organization_id,branch_id));
create policy allocations_scope on public.payment_allocations for select to authenticated using(public.has_permission('payments.review',organization_id));
create policy subscriptions_scope on public.subscriptions for select to authenticated using(public.has_permission('subscriptions.view',organization_id) and public.can_access_branch(organization_id,branch_id));
create policy freezes_scope on public.subscription_freezes for select to authenticated using(exists(select 1 from public.subscriptions s where s.id=subscription_id));
create policy cancellations_scope on public.subscription_cancellations for select to authenticated using(exists(select 1 from public.subscriptions s where s.id=subscription_id));
create policy refunds_scope on public.refunds for select to authenticated using((requested_by=auth.uid() or public.has_permission('refunds.approve',organization_id)) and public.can_access_branch(organization_id,branch_id));
create policy planned_days_scope on public.planned_service_days for select to authenticated using(exists(select 1 from public.subscriptions s where s.id=subscription_id));
create policy confirmations_scope on public.service_delivery_confirmations for select to authenticated using(exists(select 1 from public.subscriptions s where s.id=subscription_id));
create policy revenue_scope on public.revenue_entries for select to authenticated using(public.has_permission('revenue.view',organization_id));

insert into public.schema_versions(version,name) values(7,'sales_finance_subscriptions');
commit;
