begin;

create extension if not exists btree_gist with schema extensions;

insert into public.roles(code,name,description,is_system) values('doctor','Doctor','Doctor self-service sessions, notes and earnings',true) on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('dashboard.view','notifications.view','tasks.view_own','tasks.respond','doctors.view','doctors.manage_availability','sessions.view_own','sessions.complete','sessions.write_notes','sessions.view_medical_notes','doctor_commissions.view_own') where r.code='doctor' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('doctors.view','doctors.manage','doctors.manage_availability','sessions.create','sessions.assign','sessions.view_team','sessions.reschedule','sessions.cancel') where r.code in('operations_manager','customer_service') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on p.code in('doctors.view','doctors.view_financials','doctor_commissions.review','doctor_commissions.approve','doctor_commissions.pay','doctor_commissions.reverse') where r.code in('finance_manager','finance_accountant') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.code='ceo_super_admin' on conflict do nothing;

create table public.specialties(
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null,name text not null,is_active boolean not null default true,is_demo boolean not null default false,unique(organization_id,code)
);
create table public.doctors(
  id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  profile_id uuid references public.profiles(id), doctor_number bigint generated by default as identity, full_name text not null,mobile text,email extensions.citext,
  qualifications text,license_information text,bio text,languages text[] not null default '{}',gender text,consultation_types text[] not null default '{}',
  online_enabled boolean not null default true,onsite_enabled boolean not null default true,standard_session_price numeric(18,2),status text not null default 'active' check(status in('active','inactive')),
  contract_start date,contract_end date,maximum_sessions_per_day integer not null default 8,break_minutes integer not null default 15,
  rating numeric(3,2),cancellation_rate numeric(5,2) not null default 0,no_show_rate numeric(5,2) not null default 0,notes text,profile_photo_path text,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),is_demo boolean not null default false,
  unique(organization_id,doctor_number),check(contract_end is null or contract_start is null or contract_end>=contract_start)
);
create table public.doctor_specialties(
  doctor_id uuid not null references public.doctors(id) on delete cascade,specialty_id uuid not null references public.specialties(id),subspecialty text,is_primary boolean not null default false,is_demo boolean not null default false,primary key(doctor_id,specialty_id)
);
create table public.doctor_branches(
  doctor_id uuid not null references public.doctors(id) on delete cascade,branch_id uuid not null references public.branches(id),online_allowed boolean not null default true,onsite_allowed boolean not null default true,is_demo boolean not null default false,primary key(doctor_id,branch_id)
);
create table public.doctor_financial_profiles(
  id uuid primary key default extensions.gen_random_uuid(),doctor_id uuid not null unique references public.doctors(id) on delete cascade,
  payout_method text,bank_reference_encrypted text,contract_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),is_demo boolean not null default false
);
create table public.doctor_services(
  id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null,name text not null,specialty_id uuid references public.specialties(id),status text not null default 'active',is_demo boolean not null default false,unique(organization_id,code)
);
create table public.doctor_service_versions(
  id uuid primary key default extensions.gen_random_uuid(),service_id uuid not null references public.doctor_services(id) on delete cascade,version_number integer not null,
  duration_minutes integer not null check(duration_minutes>0),customer_price numeric(18,2) not null check(customer_price>=0),commission_type text not null check(commission_type in('fixed','percent_net','percent_confirmed_cash')),
  commission_value numeric(18,4) not null check(commission_value>=0),branch_id uuid references public.branches(id),delivery_mode text not null check(delivery_mode in('online','onsite','both')),
  tax_treatment text,requires_prepayment boolean not null default true,cancellation_policy jsonb not null default '{}'::jsonb,rescheduling_policy jsonb not null default '{}'::jsonb,
  active_from date not null,active_to date,status text not null default 'active',is_demo boolean not null default false,unique(service_id,version_number)
);
create table public.doctor_availability_rules(
  id uuid primary key default extensions.gen_random_uuid(),doctor_id uuid not null references public.doctors(id) on delete cascade,branch_id uuid references public.branches(id),
  day_of_week integer not null check(day_of_week between 0 and 6),start_time time not null,end_time time not null,session_duration_minutes integer not null,break_minutes integer not null default 0,
  delivery_mode text not null check(delivery_mode in('online','onsite','both')),maximum_daily_sessions integer not null default 8,minimum_notice_minutes integer not null default 120,
  effective_from date not null,effective_to date,is_active boolean not null default true,is_demo boolean not null default false,check(end_time>start_time)
);
create table public.doctor_unavailability(
  id uuid primary key default extensions.gen_random_uuid(),doctor_id uuid not null references public.doctors(id) on delete cascade,starts_at timestamptz not null,ends_at timestamptz not null,
  reason_type text not null check(reason_type in('blocked','vacation','emergency','external_conflict')),reason text,is_demo boolean not null default false,check(ends_at>starts_at)
);
create table public.doctor_slots(
  id uuid primary key default extensions.gen_random_uuid(),doctor_id uuid not null references public.doctors(id) on delete cascade,branch_id uuid references public.branches(id),
  starts_at timestamptz not null,ends_at timestamptz not null,delivery_mode text not null check(delivery_mode in('online','onsite')),status text not null default 'available' check(status in('available','held','booked','blocked')),
  hold_expires_at timestamptz,is_demo boolean not null default false,unique(doctor_id,starts_at),check(ends_at>starts_at)
);
create table public.doctor_sessions(
  id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),
  session_number bigint generated by default as identity,customer_id uuid not null references public.customers(id),doctor_id uuid references public.doctors(id),service_version_id uuid not null references public.doctor_service_versions(id),
  invoice_id uuid references public.invoices(id),payment_transaction_id uuid references public.payment_transactions(id),delivery_mode text not null check(delivery_mode in('online','onsite')),
  status text not null default 'requested' check(status in('draft','requested','doctor_matching','slot_held','awaiting_payment','payment_under_review','confirmed','calendar_pending','scheduled','reminder_sent','customer_checked_in','in_progress','completed_pending_notes','completed','customer_cancelled','doctor_cancelled','rescheduled','no_show','refund_requested','refunded','closed')),
  scheduled_start timestamptz not null,scheduled_end timestamptz not null,scheduled_range tstzrange generated always as(tstzrange(scheduled_start,scheduled_end,'[)')) stored,
  slot_hold_expires_at timestamptz,brief_reason text,customer_preference jsonb not null default '{}'::jsonb,created_by uuid not null references public.profiles(id),
  completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),is_demo boolean not null default false,
  unique(organization_id,session_number),check(scheduled_end>scheduled_start)
);
alter table public.doctor_sessions add constraint doctor_sessions_no_double_booking exclude using gist(doctor_id with =,scheduled_range with &&) where(doctor_id is not null and status in('slot_held','confirmed','calendar_pending','scheduled','reminder_sent','customer_checked_in','in_progress','completed_pending_notes'));
create table public.session_assignments(
  id uuid primary key default extensions.gen_random_uuid(),session_id uuid not null references public.doctor_sessions(id) on delete cascade,doctor_id uuid not null references public.doctors(id),
  selection_method text not null check(selection_method in('round_robin','least_loaded','fixed_doctor','customer_selected','manual','specialty_queue')),
  rotation_position integer,assigned_by uuid references public.profiles(id),assigned_at timestamptz not null default now(),override_reason text,is_selected boolean not null default true,is_demo boolean not null default false
);
create table public.session_status_history(
  id uuid primary key default extensions.gen_random_uuid(),session_id uuid not null references public.doctor_sessions(id) on delete cascade,from_status text,to_status text not null,
  changed_by uuid references public.profiles(id),reason text,changed_at timestamptz not null default now(),is_demo boolean not null default false
);
create table public.session_notes(
  id uuid primary key default extensions.gen_random_uuid(),session_id uuid not null references public.doctor_sessions(id) on delete cascade,doctor_id uuid not null references public.doctors(id),
  attendance text,start_time timestamptz,end_time timestamptz,outcome text,customer_goals text,preferences text,restrictions text,
  clinical_note text,customer_visible_summary text,sales_recommendation text,operations_instruction text,followup_required boolean not null default false,escalation_required boolean not null default false,
  completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),is_demo boolean not null default false,unique(session_id)
);
create table public.doctor_recommendations(
  id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,session_id uuid not null references public.doctor_sessions(id),doctor_id uuid not null references public.doctors(id),
  customer_id uuid not null references public.customers(id),package_version_id uuid references public.package_versions(id),recommended_at timestamptz not null default now(),attribution_expires_at timestamptz,
  sales_user_id uuid references public.profiles(id),customer_decision text,decline_reason text,confirmed_payment_transaction_id uuid references public.payment_transactions(id),commission_status text not null default 'pending',is_demo boolean not null default false
);
create table public.session_feedback(
  id uuid primary key default extensions.gen_random_uuid(),session_id uuid not null unique references public.doctor_sessions(id),session_rating integer check(session_rating between 1 and 5),doctor_rating integer check(doctor_rating between 1 and 5),
  booking_experience integer check(booking_experience between 1 and 5),punctuality integer check(punctuality between 1 and 5),helpfulness integer check(helpfulness between 1 and 5),recommendation_score integer check(recommendation_score between 0 and 10),
  comment text,complaint_required boolean not null default false,followup_required boolean not null default false,consent_to_share boolean not null default false,created_at timestamptz not null default now(),is_demo boolean not null default false
);

create table public.doctor_commission_policies(
  id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,doctor_id uuid references public.doctors(id),service_id uuid references public.doctor_services(id),name text not null,is_active boolean not null default true,is_demo boolean not null default false
);
create table public.doctor_commission_policy_versions(
  id uuid primary key default extensions.gen_random_uuid(),policy_id uuid not null references public.doctor_commission_policies(id) on delete cascade,version_number integer not null,
  method text not null check(method in('fixed_session','percent_session_net','percent_confirmed_cash','fixed_referral','percent_recommended_package','tiered')),
  value numeric(18,4) not null,tiers jsonb not null default '[]'::jsonb,effective_from date not null,effective_to date,notes_required boolean not null default true,is_demo boolean not null default false,unique(policy_id,version_number)
);
create table public.doctor_commission_entries(
  id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,doctor_id uuid not null references public.doctors(id),
  session_id uuid references public.doctor_sessions(id),recommendation_id uuid references public.doctor_recommendations(id),policy_version_id uuid references public.doctor_commission_policy_versions(id),
  entry_type text not null check(entry_type in('session','recommendation','adjustment','clawback')),basis_amount numeric(18,2) not null,amount numeric(18,2) not null,
  status text not null default 'estimated' check(status in('estimated','pending_payment_confirmation','pending_session_completion','eligible','under_finance_review','approved','scheduled_for_payout','paid','partially_paid','clawback_required','reversed','disputed')),
  reviewed_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),created_at timestamptz not null default now(),is_demo boolean not null default false,
  unique(session_id,entry_type),check(approved_by is null or approved_by<>reviewed_by)
);
create table public.doctor_statements(
  id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,doctor_id uuid not null references public.doctors(id),
  period_start date not null,period_end date not null,gross_eligible numeric(18,2) not null default 0,adjustments numeric(18,2) not null default 0,clawbacks numeric(18,2) not null default 0,
  paid_amount numeric(18,2) not null default 0,outstanding_amount numeric(18,2) not null default 0,status text not null default 'draft' check(status in('draft','under_review','approved','partially_paid','paid')),
  approved_by uuid references public.profiles(id),approved_at timestamptz,payout_date date,payment_reference text,is_demo boolean not null default false,unique(doctor_id,period_start,period_end)
);
create table public.doctor_statement_lines(
  statement_id uuid not null references public.doctor_statements(id) on delete cascade,commission_entry_id uuid not null references public.doctor_commission_entries(id),amount numeric(18,2) not null,is_demo boolean not null default false,primary key(statement_id,commission_entry_id)
);
create table public.doctor_payouts(
  id uuid primary key default extensions.gen_random_uuid(),statement_id uuid not null references public.doctor_statements(id),amount numeric(18,2) not null check(amount>0),
  status text not null default 'pending_approval' check(status in('pending_approval','approved','paid','rejected')),requested_by uuid not null references public.profiles(id),approved_by uuid references public.profiles(id),paid_by uuid references public.profiles(id),
  payment_proof_reference text,paid_at timestamptz,is_demo boolean not null default false,check(approved_by is null or approved_by<>requested_by)
);

create index doctors_scope_idx on public.doctors(organization_id,status);
create index slots_search_idx on public.doctor_slots(starts_at,branch_id,delivery_mode,status);
create index sessions_calendar_idx on public.doctor_sessions(organization_id,doctor_id,scheduled_start,status);
create index doctor_commissions_idx on public.doctor_commission_entries(doctor_id,status,created_at);
create trigger doctors_set_updated_at before update on public.doctors for each row execute function public.set_updated_at();
create trigger doctor_financials_set_updated_at before update on public.doctor_financial_profiles for each row execute function public.set_updated_at();
create trigger sessions_set_updated_at before update on public.doctor_sessions for each row execute function public.set_updated_at();
create trigger session_notes_set_updated_at before update on public.session_notes for each row execute function public.set_updated_at();
create trigger audit_doctors after insert or update or delete on public.doctors for each row execute function public.audit_row_change();
create trigger audit_sessions after insert or update or delete on public.doctor_sessions for each row execute function public.audit_row_change();
create trigger audit_doctor_commissions after insert or update or delete on public.doctor_commission_entries for each row execute function public.audit_row_change();
create trigger audit_doctor_payouts after insert or update or delete on public.doctor_payouts for each row execute function public.audit_row_change();

create or replace function public.assign_session_round_robin(p_session_id uuid,p_actor_user_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_session public.doctor_sessions;v_specialty_id uuid;v_doctor_id uuid;
begin
  select * into v_session from public.doctor_sessions where id=p_session_id for update;
  if v_session.id is null then raise exception 'session not found'; end if;
  if auth.uid() is not null and not public.has_permission('sessions.assign',v_session.organization_id) then raise exception 'sessions.assign is required'; end if;
  select ds.specialty_id into v_specialty_id from public.doctor_service_versions sv join public.doctor_services ds on ds.id=sv.service_id where sv.id=v_session.service_version_id;
  select d.id into v_doctor_id from public.doctors d join public.doctor_specialties sp on sp.doctor_id=d.id and sp.specialty_id=v_specialty_id
  where d.organization_id=v_session.organization_id and d.status='active'
    and exists(select 1 from public.doctor_branches db where db.doctor_id=d.id and (v_session.branch_id is null or db.branch_id=v_session.branch_id))
    and not exists(select 1 from public.doctor_sessions s where s.doctor_id=d.id and s.status in('slot_held','confirmed','calendar_pending','scheduled','in_progress') and s.scheduled_range && v_session.scheduled_range)
  order by (select count(*) from public.doctor_sessions sx where sx.doctor_id=d.id and sx.scheduled_start::date=v_session.scheduled_start::date),d.id limit 1;
  if v_doctor_id is null then raise exception 'no eligible doctor available'; end if;
  update public.doctor_sessions set doctor_id=v_doctor_id,status=case when status='requested' then 'slot_held' else status end,slot_hold_expires_at=now()+interval '15 minutes' where id=v_session.id;
  insert into public.session_assignments(session_id,doctor_id,selection_method,assigned_by,is_demo) values(v_session.id,v_doctor_id,'round_robin',p_actor_user_id,v_session.is_demo);
  return v_doctor_id;
end; $$;

create or replace function public.complete_doctor_session(p_session_id uuid,p_actor_user_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_session public.doctor_sessions;v_notes public.session_notes;v_policy public.doctor_commission_policy_versions;v_service public.doctor_service_versions;v_entry_id uuid;v_amount numeric(18,2);
begin
  select * into v_session from public.doctor_sessions where id=p_session_id for update;
  select * into v_notes from public.session_notes where session_id=p_session_id;
  select * into v_service from public.doctor_service_versions where id=v_session.service_version_id;
  if v_session.doctor_id is null or v_session.status not in('in_progress','completed_pending_notes') then raise exception 'session is not completable'; end if;
  if v_service.requires_prepayment and v_session.payment_transaction_id is null then raise exception 'confirmed payment is required'; end if;
  if v_notes.id is null or v_notes.outcome is null then raise exception 'required session notes are incomplete'; end if;
  if auth.uid() is not null and p_actor_user_id<>auth.uid() then raise exception 'actor mismatch'; end if;
  update public.doctor_sessions set status='completed',completed_at=now() where id=v_session.id;
  select pv.* into v_policy from public.doctor_commission_policy_versions pv join public.doctor_commission_policies p on p.id=pv.policy_id
  where p.organization_id=v_session.organization_id and p.is_active and (p.doctor_id is null or p.doctor_id=v_session.doctor_id) and current_date>=pv.effective_from and (pv.effective_to is null or current_date<=pv.effective_to)
  order by(p.doctor_id is not null) desc,pv.effective_from desc limit 1;
  if v_policy.id is not null then
    v_amount:=case when v_policy.method='fixed_session' then v_policy.value else round(v_service.customer_price*v_policy.value/100,2) end;
    insert into public.doctor_commission_entries(organization_id,doctor_id,session_id,policy_version_id,entry_type,basis_amount,amount,status,is_demo)
    values(v_session.organization_id,v_session.doctor_id,v_session.id,v_policy.id,'session',v_service.customer_price,v_amount,'eligible',v_session.is_demo)
    on conflict(session_id,entry_type) do update set status=excluded.status returning id into v_entry_id;
  end if;
  perform public.enqueue_domain_event(v_session.organization_id,v_session.branch_id,'doctor_session.completed','doctor_session',v_session.id,'{}'::jsonb,p_actor_user_id,'doctor_session.completed:'||v_session.id::text,v_session.is_demo);
  return v_entry_id;
end; $$;

do $$ declare t text; begin foreach t in array array['specialties','doctors','doctor_specialties','doctor_branches','doctor_financial_profiles','doctor_services','doctor_service_versions','doctor_availability_rules','doctor_unavailability','doctor_slots','doctor_sessions','session_assignments','session_status_history','session_notes','doctor_recommendations','session_feedback','doctor_commission_policies','doctor_commission_policy_versions','doctor_commission_entries','doctor_statements','doctor_statement_lines','doctor_payouts'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy specialties_scope on public.specialties for select to authenticated using(public.has_permission('doctors.view',organization_id));
create policy doctors_scope on public.doctors for select to authenticated using(public.has_permission('doctors.view',organization_id) or profile_id=auth.uid());
create policy doctors_manage_scope on public.doctors for all to authenticated using(public.has_permission('doctors.manage',organization_id)) with check(public.has_permission('doctors.manage',organization_id));
create policy doctor_specialties_scope on public.doctor_specialties for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id));
create policy doctor_branches_scope on public.doctor_branches for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id));
create policy doctor_financials_scope on public.doctor_financial_profiles for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id and (d.profile_id=auth.uid() or public.has_permission('doctors.view_financials',d.organization_id))));
create policy doctor_services_scope on public.doctor_services for select to authenticated using(public.has_permission('doctors.view',organization_id));
create policy doctor_service_versions_scope on public.doctor_service_versions for select to authenticated using(exists(select 1 from public.doctor_services s where s.id=service_id));
create policy availability_scope on public.doctor_availability_rules for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id));
create policy unavailability_scope on public.doctor_unavailability for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id));
create policy slots_scope on public.doctor_slots for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id));
create policy sessions_scope on public.doctor_sessions for select to authenticated using(public.has_permission('sessions.view_team',organization_id) or exists(select 1 from public.doctors d where d.id=doctor_id and d.profile_id=auth.uid()));
create policy session_assignments_scope on public.session_assignments for select to authenticated using(exists(select 1 from public.doctor_sessions s where s.id=session_id));
create policy session_history_scope on public.session_status_history for select to authenticated using(exists(select 1 from public.doctor_sessions s where s.id=session_id));
create policy session_notes_scope on public.session_notes for select to authenticated using(exists(select 1 from public.doctors d where d.id=doctor_id and (d.profile_id=auth.uid() or public.has_permission('sessions.view_medical_notes',d.organization_id))));
create policy recommendations_scope on public.doctor_recommendations for select to authenticated using(public.is_organization_member(organization_id));
create policy feedback_scope on public.session_feedback for select to authenticated using(exists(select 1 from public.doctor_sessions s where s.id=session_id));
create policy doctor_policy_scope on public.doctor_commission_policies for select to authenticated using(public.has_permission('doctor_commissions.review',organization_id));
create policy doctor_policy_versions_scope on public.doctor_commission_policy_versions for select to authenticated using(exists(select 1 from public.doctor_commission_policies p where p.id=policy_id and public.has_permission('doctor_commissions.review',p.organization_id)));
create policy doctor_commissions_scope on public.doctor_commission_entries for select to authenticated using(public.has_permission('doctor_commissions.review',organization_id) or exists(select 1 from public.doctors d where d.id=doctor_id and d.profile_id=auth.uid()));
create policy doctor_statements_scope on public.doctor_statements for select to authenticated using(public.has_permission('doctor_commissions.review',organization_id) or exists(select 1 from public.doctors d where d.id=doctor_id and d.profile_id=auth.uid()));
create policy statement_lines_scope on public.doctor_statement_lines for select to authenticated using(exists(select 1 from public.doctor_statements s where s.id=statement_id));
create policy doctor_payouts_scope on public.doctor_payouts for select to authenticated using(exists(select 1 from public.doctor_statements s where s.id=statement_id));

insert into public.schema_versions(version,name) values(9,'doctors_sessions_accounting');
commit;
