begin;
create table if not exists public.eco_notification_comments(id uuid primary key default gen_random_uuid(),notification_id uuid not null references public.eco_notifications(id) on delete cascade,actor_id uuid not null references public.eco_employees(id),body text not null check(length(body) between 1 and 2000),created_at timestamptz not null default now());
alter table public.eco_notification_comments enable row level security;
revoke all on public.eco_notification_comments from public,anon,authenticated;grant select,insert on public.eco_notification_comments to service_role;

create or replace function public.eco_add_notification_comment(p_actor_id uuid,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_id uuid;begin perform public.eco_require_actor(p_actor_id,'notifications.read');if not exists(select 1 from public.eco_notifications n where n.id=(p_payload->>'notification_id')::uuid and(n.employee_id=p_actor_id or public.eco_actor_has_permission(p_actor_id,'*'))) then raise exception 'ECO_NOTIFICATION_FORBIDDEN' using errcode='42501';end if;insert into public.eco_notification_comments(notification_id,actor_id,body) values((p_payload->>'notification_id')::uuid,p_actor_id,trim(p_payload->>'body')) returning id into v_id;return jsonb_build_object('comment_id',v_id);end $$;

create or replace function public.eco_request_cancellation(p_actor_id uuid,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_sub public.eco_subscriptions%rowtype;v_request uuid;v_cancel uuid;v_remaining numeric(14,2);v_consumed numeric(14,2);v_penalty numeric(14,2);v_delivery_days integer;v_delivery_penalty numeric(14,2);v_refund numeric(14,2);begin
perform public.eco_require_actor(p_actor_id,'subscriptions.change.preview');select * into strict v_sub from public.eco_subscriptions where id=(p_payload->>'subscription_id')::uuid and status in('ACTIVE','PAUSED') for update;
if exists(select 1 from public.eco_subscription_change_requests where idempotency_key=p_payload->>'idempotency_key') then select id into v_request from public.eco_subscription_change_requests where idempotency_key=p_payload->>'idempotency_key';select id into v_cancel from public.eco_cancellations where change_request_id=v_request;return jsonb_build_object('request_id',v_request,'cancellation_id',v_cancel,'duplicate',true);end if;
select coalesce(sum((granted_quantity-consumed_quantity-reserved_quantity)*obligation_unit_value),0),coalesce(sum(consumed_quantity*obligation_unit_value),0) into v_remaining,v_consumed from public.eco_entitlements where subscription_id=v_sub.id;select count(distinct service_date) into v_delivery_days from public.eco_fulfillments where subscription_id=v_sub.id and status='DELIVERED';v_penalty:=round(v_consumed*.20,2);v_delivery_penalty:=v_delivery_days*30;v_refund:=greatest(v_remaining-v_penalty-v_delivery_penalty,0);
insert into public.eco_subscription_change_requests(subscription_id,change_type,requested_payload,preview_snapshot,status,requested_by,idempotency_key,reason) values(v_sub.id,'CANCEL',p_payload,jsonb_build_object('remaining_value',v_remaining,'consumed_value',v_consumed,'consumed_penalty',v_penalty,'delivered_days',v_delivery_days,'delivery_penalty',v_delivery_penalty,'refund_amount',v_refund),'PENDING_APPROVAL',p_actor_id,p_payload->>'idempotency_key',p_payload->>'reason') returning id into v_request;
insert into public.eco_cancellations(subscription_id,change_request_id,remaining_value,consumed_value,penalty_amount,delivery_penalty,refund_amount,policy_version,status,statement_snapshot) values(v_sub.id,v_request,v_remaining,v_consumed,v_penalty,v_delivery_penalty,v_refund,'ECO-CANCEL-20PCT-30EGP-v1','REQUESTED',jsonb_build_object('remaining_value',v_remaining,'consumed_value',v_consumed,'penalty_20_percent',v_penalty,'delivered_days',v_delivery_days,'delivery_penalty_30_per_day',v_delivery_penalty,'refund_amount',v_refund,'reason',p_payload->>'reason')) returning id into v_cancel;
insert into public.eco_notifications(employee_id,title,body,priority,entity_type,entity_id,deep_link,due_at) select distinct era.employee_id,'طلب إلغاء يحتاج مراجعة','راجع حسبة الإلغاء والاسترداد للعميل قبل تنفيذ الإلغاء.','HIGH','cancellation',v_cancel,'/accounting',now()+interval '1 day' from public.eco_employee_role_assignments era where era.role_code in('accountant','finance_controller') and era.approved and era.effective_from<=current_date and(era.effective_to is null or era.effective_to>=current_date);
return jsonb_build_object('request_id',v_request,'cancellation_id',v_cancel,'refund_amount',v_refund,'status','PENDING_ACCOUNTING');end $$;

create or replace function public.eco_review_cancellation(p_actor_id uuid,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_cancel public.eco_cancellations%rowtype;v_approved boolean:=(p_payload->>'approved')::boolean;begin perform public.eco_require_actor(p_actor_id,'payments.verify');select * into strict v_cancel from public.eco_cancellations where id=(p_payload->>'cancellation_id')::uuid for update;if v_cancel.status<>'REQUESTED' then return jsonb_build_object('cancellation_id',v_cancel.id,'duplicate',true,'status',v_cancel.status);end if;if not v_approved then update public.eco_cancellations set status='REJECTED',reviewed_by=p_actor_id,reviewed_at=now() where id=v_cancel.id;update public.eco_subscription_change_requests set status='REJECTED',approved_by=p_actor_id,approved_at=now() where id=v_cancel.change_request_id;return jsonb_build_object('cancellation_id',v_cancel.id,'status','REJECTED');end if;update public.eco_cancellations set status='APPROVED',reviewed_by=p_actor_id,reviewed_at=now() where id=v_cancel.id;update public.eco_subscription_change_requests set status='COMMITTED',approved_by=p_actor_id,approved_at=now(),committed_at=now() where id=v_cancel.change_request_id;update public.eco_subscriptions set status='CANCELED',canceled_at=now(),updated_at=now() where id=v_cancel.subscription_id;update public.eco_fulfillments set status='CANCELED',updated_at=now() where subscription_id=v_cancel.subscription_id and service_date>=current_date and status in('PLANNED','READY_FOR_KITCHEN','QA_RELEASED','PACKED','READY_FOR_DISPATCH');update public.eco_sales_credit_events set lifecycle_state=case when lifecycle_state='PAYMENT_VERIFIED_PENDING_MATURITY' then 'CANCELED_BEFORE_MATURITY' else 'REVERSED_AFTER_MATURITY' end where order_id=(select order_id from public.eco_subscriptions where id=v_cancel.subscription_id) and lifecycle_state in('PAYMENT_VERIFIED_PENDING_MATURITY','ELIGIBLE_CONFIRMED');insert into public.eco_subscription_events(subscription_id,event_type,effective_at,actor_id,source_type,source_id,payload,idempotency_key) values(v_cancel.subscription_id,'CANCEL',now(),p_actor_id,'cancellation',v_cancel.id,v_cancel.statement_snapshot,'cancel-approved:'||v_cancel.id) on conflict(idempotency_key) do nothing;insert into public.eco_outbox_events(event_type,aggregate_type,aggregate_id,payload) values('CANCELLATION_APPROVED','cancellation',v_cancel.id::text,jsonb_build_object('subscription_id',v_cancel.subscription_id,'refund_amount',v_cancel.refund_amount));return jsonb_build_object('cancellation_id',v_cancel.id,'status','APPROVED','refund_amount',v_cancel.refund_amount);end $$;

create or replace view public.eco_cancellation_queue_v with(security_invoker=false) as select ca.id,ca.id cancellation_id,s.subscription_number,c.full_name customer_name,ca.remaining_value,ca.consumed_value,ca.penalty_amount,ca.delivery_penalty,ca.refund_amount,ca.policy_version,ca.status,cr.reason,ca.created_at from public.eco_cancellations ca join public.eco_subscriptions s on s.id=ca.subscription_id join public.eco_customers c on c.id=s.customer_id join public.eco_subscription_change_requests cr on cr.id=ca.change_request_id where ca.status='REQUESTED';
drop view if exists public.eco_notifications_v;
create view public.eco_notifications_v with(security_invoker=false) as select n.id,n.employee_id scope_employee_id,n.title,n.body,n.priority,n.due_at,n.status,n.created_at,(select count(*) from public.eco_notification_comments nc where nc.notification_id=n.id) comment_count,(select nc.body from public.eco_notification_comments nc where nc.notification_id=n.id order by nc.created_at desc limit 1) latest_comment from public.eco_notifications n;
revoke all on function public.eco_add_notification_comment(uuid,jsonb),public.eco_request_cancellation(uuid,jsonb),public.eco_review_cancellation(uuid,jsonb) from public,anon,authenticated;grant execute on function public.eco_add_notification_comment(uuid,jsonb),public.eco_request_cancellation(uuid,jsonb),public.eco_review_cancellation(uuid,jsonb) to service_role;
revoke all on public.eco_cancellation_queue_v,public.eco_notifications_v from public,anon,authenticated;grant select on public.eco_cancellation_queue_v,public.eco_notifications_v to service_role;
insert into public.eco_schema_migrations(version,description,checksum) values('015_cancellations_notifications','Accounting-approved cancellation calculator and notification comments','sha256:eco-v5-015-cancellations-notifications') on conflict(version) do update set description=excluded.description,checksum=excluded.checksum,applied_at=now();select pg_notify('pgrst','reload schema');commit;
