"use client";
import { LockKeyhole, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { commissionRate, useERP } from "@/components/erp-provider";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { money } from "@/lib/files";

const tiers=[["< 80%","0%"],["80–100%","3%"],["100–120%","3.5%"],["120–150%","4%"],["> 150%","5%"]];
export default function SalesPage(){const erp=useERP();const sales=erp.employees.filter((x)=>x.role==="sales");return <AppShell title="المبيعات والعمولات" subtitle="Target مقابل الإيراد المؤكد بعد استهلاك أكثر من 50%">
  <div className="mb-4 flex items-start gap-3 rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-blue-900"><LockKeyhole size={21} className="shrink-0"/><p>الإيراد يظل Locked حتى يستهلك العميل أكثر من نصف أيام الاشتراك. عندها فقط يدخل في تحقيق Target والعمولة.</p></div>
  <div className="grid gap-4 xl:grid-cols-2">{sales.map((rep)=>{const target=erp.salesTargets.find((x)=>x.employeeId===rep.id)?.target??0;const subs=erp.subscriptions.filter((sub)=>erp.orders.find((o)=>o.id===sub.orderId)?.salesRepId===rep.id);const confirmed=subs.filter((x)=>x.consumedDays/x.totalDays>.5);const revenue=confirmed.reduce((sum,sub)=>sum+(erp.orders.find((x)=>x.id===sub.orderId)?.amount??0),0);const percent=target?revenue/target*100:0;const rate=commissionRate(percent);return <Card key={rep.id}><CardHeader><div className="flex items-center justify-between"><div><small>Sales Rep</small><CardTitle className="mt-1">{rep.name}</CardTitle></div><span className="flex size-12 items-center justify-center rounded bg-[#e8f6ee] text-[#16794a]"><TrendingUp/></span></div></CardHeader><CardContent><div className="grid grid-cols-2 gap-3"><div className="metric"><small>Target</small><b>{money(target)}</b></div><div className="metric bg-[#e8f6ee]"><small>Confirmed Revenue</small><b>{money(revenue)}</b></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-[#e1e9e4]"><div className="h-full bg-[#16794a]" style={{width:`${Math.min(percent,100)}%`}}/></div><div className="mt-2 flex justify-between text-sm font-bold"><span>{percent.toFixed(1)}% Achieved</span><Badge>{rate}% Commission</Badge></div><div className="mt-4 flex justify-between rounded border p-4"><b>العمولة الحالية</b><strong className="text-xl text-[#16794a]">{money(revenue*rate/100)}</strong></div><p className="mt-3 text-xs text-[#66736b]">{confirmed.length} من {subs.length} اشتراك فتح الإيراد المؤكد.</p></CardContent></Card>})}</div>
  <Card className="mt-4"><CardHeader><CardTitle>شرائح العمولة المعتمدة</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{tiers.map(([range,rate])=><div key={range} className="rounded bg-[#f3f7f4] p-4 text-center"><small>{range}</small><b className="mt-2 block text-2xl text-[#16794a]">{rate}</b></div>)}</CardContent></Card>
  <Card className="mt-4"><CardHeader><CardTitle>فتح الإيراد حسب الاشتراك</CardTitle></CardHeader><CardContent className="space-y-2">{erp.subscriptions.map((sub)=>{const client=erp.clients.find((x)=>x.id===sub.clientId);const order=erp.orders.find((x)=>x.id===sub.orderId);const unlocked=sub.consumedDays/sub.totalDays>.5;return <div key={sub.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3 text-sm"><span><b>{client?.name}</b> · {sub.consumedDays}/{sub.totalDays} يوم</span><Badge variant={unlocked?"default":"gray"}>{unlocked?`${money(order?.amount??0)} Confirmed`:"Locked"}</Badge></div>})}</CardContent></Card>
  </AppShell>}
