"use client";
import { useState } from "react";
import { CheckCircle2, Download, ExternalLink, FileCheck2, ShieldAlert, XCircle } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DocumentSheet } from "@/components/document-sheet";
import { useERP } from "@/components/erp-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { downloadElementPdf, money } from "@/lib/files";
import type { Cancellation } from "@/lib/erp-types";

export default function AccountingPage() {
  const erp = useERP(); const [message,setMessage]=useState(""); const [actual,setActual]=useState<Record<string,number>>({}); const [receipts,setReceipts]=useState<Record<string,string>>({}); const [statement,setStatement]=useState<Cancellation|null>(null);
  const pending=erp.payments.filter((x)=>x.status==="Pending"); const remainingFunds=erp.subscriptions.reduce((sum,sub)=>{const order=erp.orders.find((x)=>x.id===sub.orderId);return sum+(order?(order.amount/sub.totalDays)*(sub.totalDays-sub.consumedDays):0)},0); const deliveredValue=erp.subscriptions.reduce((sum,sub)=>{const order=erp.orders.find((x)=>x.id===sub.orderId);return sum+(order?(order.amount/sub.totalDays)*sub.consumedDays:0)},0); const expectedCash=erp.deliveries.filter((x)=>x.date===new Date().toISOString().slice(0,10)).reduce((s,x)=>s+x.codExpected,0); const actualCash=erp.deliveries.filter((x)=>x.date===new Date().toISOString().slice(0,10)).reduce((s,x)=>s+x.cashCollected,0);
  async function doVerify(id:string){setMessage((await erp.verifyPayment(id)).message)} async function doReject(id:string){setMessage((await erp.rejectPayment(id)).message)} async function pdf(item:Cancellation){setStatement(item);setTimeout(()=>downloadElementPdf("cancellation-sheet",`Cancellation-${item.id}.pdf`),100)}
  return <AppShell title="الحسابات والـGatekeeper" subtitle="لا تشغيل قبل اعتماد الدفع، مع الإقفال اليومي والإلغاءات">
    {message?<p className="mb-4 rounded bg-[#e8f6ee] p-3 text-sm font-bold text-[#0f603a]">{message}</p>:null}
    <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="metric"><small>أموال العملاء المتبقية</small><b className="text-2xl">{money(remainingFunds)}</b></div><div className="metric"><small>قيمة أيام تم تسليمها</small><b className="text-2xl">{money(deliveredValue)}</b></div><div className="metric"><small>Pending Verification</small><b className="text-2xl text-orange-700">{pending.length}</b></div><div className="metric"><small>طلبات إلغاء مفتوحة</small><b className="text-2xl">{erp.cancellations.filter((x)=>x.status!=="Transferred").length}</b></div></div>
    <Tabs defaultValue="gate"><TabsList className="w-full sm:w-auto"><TabsTrigger value="gate">بوابة الدفع</TabsTrigger><TabsTrigger value="closing">الإقفال اليومي</TabsTrigger><TabsTrigger value="cancellations">الإلغاءات</TabsTrigger></TabsList>
      <TabsContent value="gate"><div className="mb-3 flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-900"><ShieldAlert size={20}/>أي طلب هنا ممنوع من Kitchen وDelivery حتى الضغط على اعتماد.</div><div className="space-y-3">{pending.map((payment)=>{const order=erp.orders.find((x)=>x.id===payment.orderId);const client=erp.clients.find((x)=>x.id===payment.clientId);return <Card key={payment.id}><CardContent className="pt-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap gap-2"><h2 className="text-lg font-black">{client?.name}</h2><Badge variant="orange">Pending Accounting</Badge><Badge variant="blue">{payment.method}</Badge></div><p className="mt-2 font-bold" dir="ltr">{order?.orderNumber}</p><p className="mt-1 text-sm text-[#66736b]">{money(payment.amount)} · Reference: {payment.referenceId??"Cash / COD"}</p>{payment.proofName?<p className="mt-2 inline-flex items-center gap-2 rounded bg-[#eef4f0] px-3 py-2 text-sm"><FileCheck2 size={16}/>{payment.proofName}</p>:null}</div><div className="flex gap-2"><Button onClick={()=>doVerify(payment.id)}><CheckCircle2 size={18}/>{payment.method==="Cash"?"اعتماد كـCOD":"تأكيد الدفع"}</Button><Button variant="destructive" onClick={()=>doReject(payment.id)}><XCircle size={18}/>رفض</Button></div></div></CardContent></Card>})}{!pending.length?<div className="rounded-lg border bg-white p-10 text-center text-[#66736b]">لا توجد دفعات تنتظر المراجعة.</div>:null}</div></TabsContent>
      <TabsContent value="closing"><div className="grid gap-4 lg:grid-cols-3"><Card><CardContent className="pt-5"><small>Expected Cash من الكباتن</small><b className="mt-2 block text-3xl">{money(expectedCash)}</b></CardContent></Card><Card><CardContent className="pt-5"><small>Actual Cash المسجل</small><b className="mt-2 block text-3xl">{money(actualCash)}</b></CardContent></Card><Card className={expectedCash===actualCash?"border-[#5cad7a]":"border-red-200"}><CardContent className="pt-5"><small>الفرق</small><b className={`mt-2 block text-3xl ${expectedCash===actualCash?"text-[#16794a]":"text-red-700"}`}>{money(actualCash-expectedCash)}</b></CardContent></Card></div><div className="mt-4 space-y-3">{erp.reconciliations.map((rec)=><Card key={rec.id}><CardContent className="pt-5"><div className="grid gap-3 lg:grid-cols-[1fr_1fr_1fr_auto]"><div className="metric"><small>التاريخ</small><b>{rec.date}</b></div><div className="metric"><small>المتوقع</small><b>{money(rec.expectedCash||expectedCash)}</b></div><Input type="number" value={actual[rec.id]??actualCash} onChange={(e)=>setActual({...actual,[rec.id]:Number(e.target.value)})}/><Button onClick={async()=>setMessage((await erp.closeReconciliation(rec.id,actual[rec.id]??actualCash)).message)} disabled={rec.status==="Closed"}>{rec.status==="Closed"?"اليوم مغلق":"إغلاق اليوم"}</Button></div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="cancellations"><div className="space-y-4">{erp.cancellations.map((item)=>{const client=erp.clients.find((x)=>x.id===item.clientId);return <Card key={item.id}><CardContent className="pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">{client?.name}</h2><Badge variant={item.status==="Transferred"?"default":item.status==="Reviewed"?"blue":"orange"}>{item.status}</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><div className="metric"><small>Remaining Value</small><b>{money(item.remainingValue)}</b></div><div className="metric"><small>Consumed Value</small><b>{money(item.consumedValue)}</b></div><div className="metric bg-red-50"><small>20% Penalty</small><b>-{money(item.consumedPenalty)}</b></div><div className="metric bg-red-50"><small>Delivery Penalty</small><b>-{money(item.deliveryPenalty)}</b></div><div className="metric bg-[#e8f6ee]"><small>Refund</small><b className="text-xl text-[#0f603a]">{money(item.refundAmount)}</b></div></div><p className="mt-3 text-sm"><b>السبب:</b> {item.reason}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>pdf(item)}><Download size={17}/>Cancellation PDF</Button>{item.status==="Requested"?<Button onClick={async()=>setMessage((await erp.reviewCancellation(item.id)).message)}><FileCheck2 size={17}/>مراجعة الحساب</Button>:null}{item.status==="Reviewed"?<><label className="inline-flex min-h-11 cursor-pointer items-center rounded border px-3 text-sm font-bold">{receipts[item.id]||"رفع إيصال التحويل"}<input type="file" className="hidden" onChange={(e)=>setReceipts({...receipts,[item.id]:e.target.files?.[0]?.name??""})}/></label><Button onClick={async()=>setMessage((await erp.transferCancellation(item.id,receipts[item.id]??"")).message)} disabled={!receipts[item.id]}>تأكيد التحويل</Button></>:null}{item.status==="Transferred"&&item.receiptName?<span className="inline-flex items-center gap-1 text-sm font-bold text-[#16794a]"><ExternalLink size={15}/>{item.receiptName}</span>:null}</div></CardContent></Card>})}{!erp.cancellations.length?<div className="rounded-lg border bg-white p-10 text-center text-[#66736b]">لا توجد طلبات إلغاء.</div>:null}</div></TabsContent>
    </Tabs>
    {statement?<DocumentSheet id="cancellation-sheet" title="بيان إلغاء رسمي" number={statement.id}><div className="rounded bg-[#f3f7f4] p-5"><b>العميل: {erp.clients.find((x)=>x.id===statement.clientId)?.name}</b><p className="mt-2">سبب الإلغاء: {statement.reason}</p></div><table className="mt-8 w-full text-sm"><tbody>{[["Remaining Value",statement.remainingValue],["Consumed Value",statement.consumedValue],["20% Consumed Penalty",-statement.consumedPenalty],["Delivery Days Penalty",-statement.deliveryPenalty],["Final Refund",statement.refundAmount]].map(([label,value])=><tr key={String(label)} className="border-b"><td className="p-4 font-bold">{label}</td><td className="p-4 text-left text-lg font-black">{money(Number(value))}</td></tr>)}</tbody></table><p className="mt-8 text-sm leading-7">هذا البيان صادر آليًا من نظام ECO Healthy بعد مراجعة الأيام المستهلكة والتوصيلات المسجلة.</p></DocumentSheet>:null}
  </AppShell>;
}
