"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ExternalLink, MessageSquarePlus, Phone, Truck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { HelpTip } from "@/components/help-tip";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { createClient } from "@/lib/supabase/client";
import type { ClientSummaryRow, OrderRow, SubscriptionRow } from "@/lib/domain";

type History={id:string;delivery_date:string;delivered_at:string|null;delivered_day_number:number|null;order_number:string;status:string;zone:number};
type Issue={id:string;category:string;note:string;image_url:string|null;resolved:boolean;created_at:string};

export default function ClientDetailPage(){
  const {id}=useParams<{id:string}>(); const supabase=useMemo(()=>createClient(),[]); const [client,setClient]=useState<ClientSummaryRow|null>(null); const [orders,setOrders]=useState<OrderRow[]>([]); const [subs,setSubs]=useState<SubscriptionRow[]>([]); const [history,setHistory]=useState<History[]>([]); const [issues,setIssues]=useState<Issue[]>([]); const [diet,setDiet]=useState(""); const [issue,setIssue]=useState(""); const [imageUrl,setImageUrl]=useState(""); const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const [c,o,s,h,i]=await Promise.all([supabase.from("client_360_summary").select("*").eq("id",id).single(),supabase.from("orders").select("id,order_number,client_id,order_type,total_price,payment_method,payment_reference,payment_proof_path,status,accounting_verified_at,created_at").eq("client_id",id).order("created_at",{ascending:false}),supabase.from("subscriptions").select("id,client_id,order_id,package_id,status,start_date,delivery_frequency,weekly_delivery_day,total_days,consumed_days,remaining_days,pause_until,packages(name,size_name,price),orders(order_number,status,total_price)").eq("client_id",id),supabase.from("delivery_history").select("*").eq("client_id",id).order("delivery_date",{ascending:false}),supabase.from("client_issues").select("*").eq("client_id",id).order("created_at",{ascending:false})]);setClient(c.data as ClientSummaryRow);setDiet((c.data as any)?.dietary_notes??"");setOrders((o.data??[]) as OrderRow[]);setSubs((s.data??[]) as unknown as SubscriptionRow[]);setHistory((h.data??[]) as History[]);setIssues((i.data??[]) as Issue[])},[id,supabase]); useEffect(()=>{void load()},[load]);
  async function saveDiet(){const {error}=await supabase.from("clients").update({dietary_notes:diet}).eq("id",id);setMessage(error?.message??"تم حفظ القواعد الغذائية");await load()}
  async function addIssue(){if(!issue.trim())return;const {error}=await supabase.from("client_issues").insert({client_id:id,category:"complaint",note:issue.trim(),image_url:imageUrl.trim()||null});setMessage(error?.message??"تم تسجيل الشكوى");if(!error){setIssue("");setImageUrl("");await load()}}
  async function requestCancel(subId:string){const {error}=await supabase.rpc("request_cancellation",{p_subscription_id:subId,p_notes:"Requested from Client 360"});setMessage(error?.message??"تم إرسال طلب الإلغاء للحسابات")}
  if(!client)return <AppShell title="Client 360" subtitle="جاري تحميل ملف العميل..."><p>Loading...</p></AppShell>;
  return <AppShell title={client.full_name} subtitle={`Client 360 · ${client.phone}`}>
    {message?<div className="mb-4 rounded-md bg-blue-50 p-3 text-sm font-bold text-blue-900">{message}</div>:null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card><CardContent className="pt-5"><p className="text-xs text-[#66736b]">Total Funds Paid</p><p className="mt-2 text-2xl font-black text-[#16794a]">{Number(client.total_verified_paid).toLocaleString()} ج</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs text-[#66736b]">Remaining Balance</p><p className="mt-2 text-2xl font-black">{Number(client.remaining_balance).toLocaleString()} ج</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs text-[#66736b]">Total Orders</p><p className="mt-2 text-2xl font-black">{client.total_orders}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs text-[#66736b]">Zone / Contact</p><div className="mt-2 flex items-center gap-2"><Badge>Zone {client.delivery_zone}</Badge><a href={`tel:${client.phone}`} className="text-[#16794a]"><Phone size={19}/></a>{client.location_url?<a href={client.location_url} target="_blank" rel="noreferrer" className="text-[#16794a]"><ExternalLink size={19}/></a>:null}</div></CardContent></Card></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-1">Dietary Rules <HelpTip text="هذه القواعد تظهر للمطبخ على Label العميل في كل Queue line." /></CardTitle></CardHeader><CardContent><Textarea value={diet} onChange={e=>setDiet(e.target.value)} className="min-h-32"/><Button className="mt-3" onClick={saveDiet}>حفظ القواعد</Button></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><MessageSquarePlus size={19}/>تسجيل شكوى</CardTitle></CardHeader><CardContent><Textarea value={issue} onChange={e=>setIssue(e.target.value)} placeholder="اكتب ما حدث بوضوح"/><Input className="mt-2" value={imageUrl} onChange={e=>setImageUrl(e.target.value)} placeholder="رابط صورة اختياري"/><Button className="mt-3" onClick={addIssue}>إضافة للسجل</Button></CardContent></Card></div>
    <Card className="mt-4"><CardHeader><CardTitle className="flex items-center gap-2"><Truck size={20}/>Delivery History Log <HelpTip text="السجل يأتي من عمليات التسليم الفعلية ويظهر رقم يوم الاشتراك وتاريخه لحسم أي خلاف مع العميل." /></CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b bg-[#f5f8f6]"><th className="p-3 text-right">التاريخ</th><th className="p-3 text-right">الاشتراك</th><th className="p-3 text-right">Order</th><th className="p-3 text-right">Zone</th><th className="p-3 text-right">الحالة</th></tr></thead><tbody>{history.map(h=><tr key={h.id} className="border-b border-[#e6ece8]"><td className="p-3">{h.delivery_date}</td><td className="p-3 font-bold">{h.delivered_day_number?`Delivered Day ${h.delivered_day_number}`:"Ad-Hoc"}</td><td className="p-3">{h.order_number}</td><td className="p-3">Zone {h.zone}</td><td className="p-3"><Badge variant={h.status==="delivered"?"default":"gray"}>{h.status}</Badge></td></tr>)}</tbody></table>{history.length===0?<p className="py-6 text-center text-sm text-[#748078]">لا توجد توصيلات مسجلة بعد.</p>:null}</div></CardContent></Card>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>الاشتراكات</CardTitle></CardHeader><CardContent className="space-y-2">{subs.map(s=><div key={s.id} className="rounded-md border border-[#e3eae5] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{s.packages?.name} · {s.packages?.size_name}</b><p className="mt-1 text-sm text-[#66736b]">{s.consumed_days}/{s.total_days} يوم · باقي {s.remaining_days}</p></div><div className="flex gap-2"><Badge>{s.status}</Badge>{["active","paused"].includes(s.status)?<Button size="sm" variant="destructive" onClick={()=>requestCancel(s.id)}>طلب إلغاء</Button>:null}</div></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>الشكاوى والملاحظات</CardTitle></CardHeader><CardContent className="space-y-2">{issues.map(i=><div key={i.id} className="rounded-md bg-[#f5f8f6] p-3 text-sm"><div className="flex justify-between gap-2"><b>{i.category}</b><span className="text-xs text-[#7a867e]">{new Date(i.created_at).toLocaleDateString("ar-EG")}</span></div><p className="mt-2 leading-6">{i.note}</p>{i.image_url?<a href={i.image_url} target="_blank" rel="noreferrer" className="mt-2 inline-block font-bold text-[#16794a]">فتح الصورة</a>:null}</div>)}</CardContent></Card></div>
    <Card className="mt-4"><CardHeader><CardTitle>Financial Orders</CardTitle></CardHeader><CardContent className="space-y-2">{orders.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-[#e3eae5] p-3 text-sm"><div><b>{o.order_number}</b><span className="text-[#66736b]"> · {o.order_type}</span></div><div className="flex items-center gap-3"><b>{Number(o.total_price).toLocaleString()} ج</b><Badge variant={o.status==="confirmed"?"default":"gray"}>{o.status}</Badge></div></div>)}</CardContent></Card>
  </AppShell>
}
